create table WMS_ACCOUNT
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_ACCOUNT primary key,
    ACCOUNT_CODE                 VARCHAR2(32) not null,
    WAREHOUSE_CODE               VARCHAR2(32) not null,
    WAREHOUSE_LOCATION_CODE      VARCHAR2(32) not null,
    PRODUCTION_CODE              VARCHAR2(32) not null,
    IS_PARENT                    VARCHAR2(8) DEFAULT '2',
    PRODUCE_STATUS               VARCHAR2(16),
    PARENT_PRODUCTION_CODE       VARCHAR2(32),
    PROJECT_CODE                 VARCHAR2(32),
    CONTRACT_CODE                VARCHAR2(32),
    DISPATCH_CODE                VARCHAR2(32),
    BRAND                        VARCHAR2(32),
    SPECIFICATIONS               VARCHAR2(32),
    PRODUCTION_LEVEL             VARCHAR2(32),
    TECHNICAL_CONDITIONS         VARCHAR2(64),
    ADDITIONAL_TECHNICAL_CONDITIONS VARCHAR2(64),
    THREE_PERIOD_CODE            VARCHAR2(32),
    MANUFACTURE_DATE             DATE,
    EXPIRATION_DATE              DATE,
    BATCH                        VARCHAR2(32),
    SPLYSOT_CODE                 VARCHAR2(200),
    AIRCRAFT_CODE                VARCHAR2(64),
    SORTIE_CODE                  VARCHAR2(64),
    MODEL_CODE                   VARCHAR2(64),
    CONSTRUCTION_CODE            VARCHAR2(64),
    QUALITY_CODE                 VARCHAR2(64),
    QUALITY_STATUS               VARCHAR2(32),
    STATUS                       VARCHAR2(32),
    CERTIFICATE_NO               VARCHAR2(32),
    SUPPLY_CERTIFICATE_NO        VARCHAR2(32),
    SUPPLIER_TYPE                VARCHAR2(32),
    SUPPLIER_BY                VARCHAR2(64),
    QUANTITY                     NUMBER(32,4),
    OCCUPY_QUANTITY              NUMBER(32,4),
    PRICE_CATEGORY               VARCHAR2(16),
    PRICE                        NUMBER(32,4),
    IS_CONSIGNMENT               VARCHAR2(16),
    PRODUCTION_SIZE              VARCHAR2(32),
    PRODUCTION_OWNER_CODE       VARCHAR2(32),
    PRODUCTION_OWNER_TYPE       VARCHAR2(32),
    DETAILS                     VARCHAR2(200),
    ATTRIBUTE1                  VARCHAR2(32),
    ATTRIBUTE2                  VARCHAR2(32),
    ATTRIBUTE3                  VARCHAR2(32),
    ATTRIBUTE4                  VARCHAR2(32),
    ATTRIBUTE5                  VARCHAR2(32),
    ATTRIBUTE6                  VARCHAR2(32),
    ATTRIBUTE7                  VARCHAR2(32),
    ATTRIBUTE8                  VARCHAR2(32),
    ATTRIBUTE9                  VARCHAR2(32),
    ATTRIBUTE10                 VARCHAR2(32),
    VERSION                      VARCHAR2(32)
);

comment on table WMS_ACCOUNT is '库房台账表';
comment on column WMS_ACCOUNT.ID is '表id';
comment on column WMS_ACCOUNT.ACCOUNT_CODE  is '台账编码，自动生成';
comment on column WMS_ACCOUNT.WAREHOUSE_CODE is '库房编号';
comment on column WMS_ACCOUNT.WAREHOUSE_LOCATION_CODE is '库位号';
comment on column WMS_ACCOUNT.PRODUCTION_CODE is '产品编码';
comment on column WMS_ACCOUNT.IS_PARENT is '是否为父件，0父件、1子件、2非父子件关系';
comment on column WMS_ACCOUNT.PRODUCE_STATUS is '物料制造处理状态，produce 在制品，clout 余料，waste废料';
comment on column WMS_ACCOUNT.PARENT_PRODUCTION_CODE is '父产品编码';
comment on column WMS_ACCOUNT.PROJECT_CODE is '项目编码，批次属性';
comment on column WMS_ACCOUNT.DISPATCH_CODE is '派工号，FO执行序列号';
comment on column WMS_ACCOUNT.CONTRACT_CODE is '合同编号';
comment on column WMS_ACCOUNT.BRAND is '牌号，本为物料属性，但是部分为1：n关系，目前无后期逻辑处理，仅仅记录';
comment on column WMS_ACCOUNT.SPECIFICATIONS is '规格，本为物料属性，但是部分为1：n关系，目前无后期逻辑处理，仅仅记录';
comment on column WMS_ACCOUNT.PRODUCTION_LEVEL is '状态/级别/型号，本为物料属性，但是部分为1：n关系，目前无后期逻辑处理，仅仅记录';
comment on column WMS_ACCOUNT.ADDITIONAL_TECHNICAL_CONDITIONS is '附加技术条件，本为物料属性，但是部分为1：n关系，目前无后期逻辑处理，仅仅记录';
comment on column WMS_ACCOUNT.TECHNICAL_CONDITIONS is '技术条件';
comment on column WMS_ACCOUNT.THREE_PERIOD_CODE is '三期代码，批次属性';
comment on column WMS_ACCOUNT.MANUFACTURE_DATE   is '生产日期，批次属性';
comment on column WMS_ACCOUNT.EXPIRATION_DATE is '过期日期，批次属性';
comment on column WMS_ACCOUNT.BATCH           is '批次号，批次属性';
comment on column WMS_ACCOUNT.SPLYSOT_CODE    is '炉批号或小号，批次属性';
comment on column WMS_ACCOUNT.AIRCRAFT_CODE   is '机型，批次属性';
comment on column WMS_ACCOUNT.SORTIE_CODE     is '架次，批次属性';
comment on column WMS_ACCOUNT.MODEL_CODE    is '版号，批次属性';
comment on column WMS_ACCOUNT.CONSTRUCTION_CODE is '构型号，批次属性';
comment on column WMS_ACCOUNT.QUALITY_STATUS     is '质检状态，批次属性';
comment on column WMS_ACCOUNT.QUALITY_CODE     is '质量编号，批次属性';
comment on column WMS_ACCOUNT.STATUS              is '状态，批次属性';
comment on column WMS_ACCOUNT.CERTIFICATE_NO              is '合格证号，批次属性';
comment on column WMS_ACCOUNT.SUPPLY_CERTIFICATE_NO  is '供方合格证号';
comment on column WMS_ACCOUNT.SUPPLIER_TYPE  is '提供者类型';
comment on column WMS_ACCOUNT.SUPPLIER_BY  is '提供者';
comment on column WMS_ACCOUNT.QUANTITY      is '数量';
comment on column WMS_ACCOUNT.OCCUPY_QUANTITY      is '占用数量';
comment on column WMS_ACCOUNT.PRICE_CATEGORY      is '计价规则，仅仅采购价生效，如果为计划价，则仅仅记录入库时计划价，不做处理';
comment on column WMS_ACCOUNT.PRICE      is '计价规则';
comment on column WMS_ACCOUNT.IS_CONSIGNMENT   is '是否寄售';
comment on column WMS_ACCOUNT.DETAILS                   is '备注';
comment on column WMS_ACCOUNT.PRODUCTION_SIZE                   is '物料尺寸，本身为物料属性，此处尺寸仅仅在物料状态为余料时有效';
comment on column WMS_ACCOUNT.PRODUCTION_OWNER_CODE        is '货主编码';
comment on column WMS_ACCOUNT.PRODUCTION_OWNER_TYPE        is '货主类型';

create table WMS_ACCOUNT_CERTIFICATE
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_ACCOUNT_CERTIFICATE primary key,
    ACCOUNT_CODE                 VARCHAR2(32),
    BILL_CODE                    VARCHAR2(32),
    SUB_BILL_CODE                VARCHAR2(32),
    WORK_CODE                    VARCHAR2(32) not null,
    DEAL_CODE                    VARCHAR2(32),
    MOVE_QUANTITY                NUMBER(32,4),
    BEFORE_QUANTITY              NUMBER(32,4),
    END_QUANTITY                 NUMBER(32,4),
    FROM_ORGANIZATION            VARCHAR2(32),
    TO_ORGANIZATION              VARCHAR2(32),
    PRICE_CATEGORY               VARCHAR2(16),
    MOVE_PRICE                   NUMBER(32,4),
    PRICE_UNIT                   VARCHAR2(32),
    BEFORE_PRICE                 NUMBER(32,4),
    END_PRICE                    NUMBER(32,4),
    BEFORE_STATUS                VARCHAR2(32),
    END_STATUS                   VARCHAR2(32),
    BEFORE_QUALITY_STATUS        VARCHAR2(32),
    END_QUALITY_STATUS           VARCHAR2(32),
    MOVE_OPERATOR                VARCHAR2(32),
    MOVE_DEPT                    VARCHAR2(32),
    WAREHOUSE_CODE               VARCHAR2(32) not null,
    WAREHOUSE_LOCATION_CODE      VARCHAR2(32) not null,
    PRODUCTION_CODE              VARCHAR2(32) not null,
    IS_PARENT                    VARCHAR2(8) DEFAULT '2',
    PRODUCE_STATUS               VARCHAR2(16),
    PARENT_PRODUCTION_CODE       VARCHAR2(32),
    PROJECT_CODE                 VARCHAR2(32),
    CONTRACT_CODE                VARCHAR2(32),
    DISPATCH_CODE                VARCHAR2(32),
    BRAND                        VARCHAR2(32),
    SPECIFICATIONS               VARCHAR2(32),
    PRODUCTION_LEVEL             VARCHAR2(32),
    TECHNICAL_CONDITIONS         VARCHAR2(64),
    ADDITIONAL_TECHNICAL_CONDITIONS VARCHAR2(64),
    THREE_PERIOD_CODE            VARCHAR2(32),
    MANUFACTURE_DATE             DATE,
    EXPIRATION_DATE              DATE,
    BATCH                        VARCHAR2(32),
    SPLYSOT_CODE                 VARCHAR2(200),
    AIRCRAFT_CODE                VARCHAR2(64),
    SORTIE_CODE                  VARCHAR2(64),
    MODEL_CODE                   VARCHAR2(64),
    CONSTRUCTION_CODE            VARCHAR2(64),
    QUALITY_CODE                 VARCHAR2(64),
    CERTIFICATE_NO               VARCHAR2(32),
    SUPPLY_CERTIFICATE_NO        VARCHAR2(32),
    SUPPLIER_TYPE                VARCHAR2(32),
    SUPPLIER_BY                VARCHAR2(64),
    IS_CONSIGNMENT               VARCHAR2(16),
    PRODUCTION_SIZE              VARCHAR2(32),
    PRODUCTION_OWNER_CODE       VARCHAR2(32),
    PRODUCTION_OWNER_TYPE       VARCHAR2(32),
    DETAILS                     VARCHAR2(200),
    ATTRIBUTE1                  VARCHAR2(32),
    ATTRIBUTE2                  VARCHAR2(32),
    ATTRIBUTE3                  VARCHAR2(32),
    ATTRIBUTE4                  VARCHAR2(32),
    ATTRIBUTE5                  VARCHAR2(32),
    ATTRIBUTE6                  VARCHAR2(32),
    ATTRIBUTE7                  VARCHAR2(32),
    ATTRIBUTE8                  VARCHAR2(32),
    ATTRIBUTE9                  VARCHAR2(32),
    ATTRIBUTE10                 VARCHAR2(32),
    BAR_CODE                     VARCHAR2(64),
    STORAGE_DATE                 VARCHAR2(32),
    SERIAL_NUMBER                VARCHAR2(64),
    MANUFACTURER                 VARCHAR2(64),
    PRODUCTION_INFO              VARCHAR2(255),
    PRODUCTION_CODE_INFO         VARCHAR2(64),
    VERSION                      VARCHAR2(32),
    MOVE_TIME                   DATE DEFAULT SYSDATE
);

comment on table WMS_ACCOUNT_CERTIFICATE is '库房流水，移动凭证表';
comment on column WMS_ACCOUNT_CERTIFICATE.ID is '表id';
comment on column WMS_ACCOUNT_CERTIFICATE.ACCOUNT_CODE  is '台账编码，自动生成';
comment on column WMS_ACCOUNT_CERTIFICATE.BILL_CODE is '单据编号';
comment on column WMS_ACCOUNT_CERTIFICATE.SUB_BILL_CODE is '单据子项编号';
comment on column WMS_ACCOUNT_CERTIFICATE.WORK_CODE is '事务编号';
comment on column WMS_ACCOUNT_CERTIFICATE.DEAL_CODE is '移动编号，如合同到货、紧急到货。相当于WORK_CODE的一个补充,对接系统的需要，实际操作只需要配置即可，无需理会。主要用于处理老事务处理不规范情况';
comment on column WMS_ACCOUNT_CERTIFICATE.PRODUCTION_CODE is '物料编号';
comment on column WMS_ACCOUNT_CERTIFICATE.WAREHOUSE_CODE is '库房编号';
comment on column WMS_ACCOUNT_CERTIFICATE.WAREHOUSE_LOCATION_CODE is '库位编号';
comment on column WMS_ACCOUNT_CERTIFICATE.MOVE_QUANTITY is '移动数量';
comment on column WMS_ACCOUNT_CERTIFICATE.BEFORE_QUANTITY is '移动前数量';
comment on column WMS_ACCOUNT_CERTIFICATE.END_QUANTITY is '移动后数量';
comment on column WMS_ACCOUNT_CERTIFICATE.PRICE_CATEGORY is '计价规则';
comment on column WMS_ACCOUNT_CERTIFICATE.MOVE_PRICE is '移动价格';
comment on column WMS_ACCOUNT_CERTIFICATE.PRICE_UNIT is '计价单位';
comment on column WMS_ACCOUNT_CERTIFICATE.BEFORE_PRICE is '入库时价格';
comment on column WMS_ACCOUNT_CERTIFICATE.END_PRICE is '出库时价格';
comment on column WMS_ACCOUNT_CERTIFICATE.BEFORE_STATUS is '移动前状态';
comment on column WMS_ACCOUNT_CERTIFICATE.END_STATUS is '移动后状态';
comment on column WMS_ACCOUNT_CERTIFICATE.BEFORE_QUALITY_STATUS is '移动前质量状态';
comment on column WMS_ACCOUNT_CERTIFICATE.END_QUALITY_STATUS is '移动后质量状态';
comment on column WMS_ACCOUNT_CERTIFICATE.MOVE_OPERATOR is '移动人';
comment on column WMS_ACCOUNT_CERTIFICATE.MOVE_DEPT is '移动部门';
comment on column WMS_ACCOUNT_CERTIFICATE.MOVE_TIME is '移动时间';
comment on column WMS_ACCOUNT_CERTIFICATE.IS_PARENT is '是否为父件，0父件、1子件、2非父子件关系';
comment on column WMS_ACCOUNT_CERTIFICATE.PRODUCE_STATUS is '物料制造处理状态，produce 在制品，clout 余料，waste废料';
comment on column WMS_ACCOUNT_CERTIFICATE.PARENT_PRODUCTION_CODE is '父产品编码';
comment on column WMS_ACCOUNT_CERTIFICATE.PROJECT_CODE is '项目编码，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.BRAND is '牌号，本为物料属性，但是部分为1：n关系，目前无后期逻辑处理，仅仅记录';
comment on column WMS_ACCOUNT_CERTIFICATE.SPECIFICATIONS is '规格，本为物料属性，但是部分为1：n关系，目前无后期逻辑处理，仅仅记录';
comment on column WMS_ACCOUNT_CERTIFICATE.PRODUCTION_LEVEL is '状态/级别/型号，本为物料属性，但是部分为1：n关系，目前无后期逻辑处理，仅仅记录';
comment on column WMS_ACCOUNT_CERTIFICATE.ADDITIONAL_TECHNICAL_CONDITIONS is '附加技术条件，本为物料属性，但是部分为1：n关系，目前无后期逻辑处理，仅仅记录';
comment on column WMS_ACCOUNT_CERTIFICATE.TECHNICAL_CONDITIONS is '技术条件';
comment on column WMS_ACCOUNT_CERTIFICATE.THREE_PERIOD_CODE is '三期代码，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.MANUFACTURE_DATE   is '生产日期，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.EXPIRATION_DATE is '过期日期，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.BATCH           is '批次号，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.SPLYSOT_CODE    is '炉批号或小号，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.AIRCRAFT_CODE   is '机型，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.SORTIE_CODE     is '架次，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.MODEL_CODE    is '版号，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.CONSTRUCTION_CODE is '构型号，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.QUALITY_CODE     is '质量编号，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.CERTIFICATE_NO              is '合格证号，批次属性';
comment on column WMS_ACCOUNT_CERTIFICATE.SUPPLY_CERTIFICATE_NO  is '供方合格证号';
comment on column WMS_ACCOUNT_CERTIFICATE.IS_CONSIGNMENT   is '是否寄售';
comment on column WMS_ACCOUNT_CERTIFICATE.BAR_CODE is '条码';
comment on column WMS_ACCOUNT_CERTIFICATE.STORAGE_DATE is '封存日期';
comment on column WMS_ACCOUNT_CERTIFICATE.SERIAL_NUMBER is '成品序列号';
comment on column WMS_ACCOUNT_CERTIFICATE.MANUFACTURER is '成品序列号';
comment on column WMS_ACCOUNT_CERTIFICATE.PRODUCTION_INFO is '产品信息';
comment on column WMS_ACCOUNT_CERTIFICATE.PRODUCTION_CODE_INFO is '物品码';
comment on column WMS_ACCOUNT_CERTIFICATE.PRODUCTION_SIZE                   is '物料尺寸，本身为物料属性，此处尺寸仅仅在物料状态为余料时有效';
comment on column WMS_ACCOUNT_CERTIFICATE.PRODUCTION_OWNER_CODE        is '货主编码';
comment on column WMS_ACCOUNT_CERTIFICATE.PRODUCTION_OWNER_TYPE        is '货主类型';
comment on column WMS_ACCOUNT_CERTIFICATE.FROM_ORGANIZATION             is '移动前组织';
comment on column WMS_ACCOUNT_CERTIFICATE.TO_ORGANIZATION               is '移动后组织';
comment on column WMS_ACCOUNT_CERTIFICATE.CONTRACT_CODE                is '合同号';
comment on column WMS_ACCOUNT_CERTIFICATE.DISPATCH_CODE                is '构型号';
comment on column WMS_ACCOUNT_CERTIFICATE.SUPPLIER_TYPE                is '提供者类型';
comment on column WMS_ACCOUNT_CERTIFICATE.SUPPLIER_BY                is '提供者';


create table CONFIG_AFTER_DEAL
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint CONFIG_AFTER_DEAL primary key,
    CONFIG_CODE     VARCHAR2(32) not null,
    SYSTEM_FROM          VARCHAR2(32),
    WAREHOUSE_WORK_CODE  VARCHAR2(32) not null,
    WAREHOUSE_DEAL_CODE VARCHAR2(32),
    STATUS             VARCHAR2(16),
    REBACK_URL         VARCHAR2(255),
    VERSION            VARCHAR(32),
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null
);

comment on table CONFIG_AFTER_DEAL is '后处理配置';
comment on column CONFIG_AFTER_DEAL.ID is '表id';
comment on column CONFIG_AFTER_DEAL.CONFIG_CODE is '配置编号';
comment on column CONFIG_AFTER_DEAL.SYSTEM_FROM is '系统来源';
comment on column CONFIG_AFTER_DEAL.WAREHOUSE_WORK_CODE is '事务编号';
comment on column CONFIG_AFTER_DEAL.WAREHOUSE_DEAL_CODE is '处理类型编号，如合同到货、紧急到货。相当于WORK_CODE的一个补充,对接系统的需要，实际操作只需要配置即可，无需理会，主要用于处理老事务处理不规范情况';
comment on column CONFIG_AFTER_DEAL.STATUS  is '配置状态';
comment on column CONFIG_AFTER_DEAL.REBACK_URL  is '回掉接口地址';
comment on column CONFIG_AFTER_DEAL.VERSION is '版本';
comment on column CONFIG_AFTER_DEAL.CREATED_BY is '创建人';
comment on column CONFIG_AFTER_DEAL.CREATED_DATE is '创建时间';
comment on column CONFIG_AFTER_DEAL.LAST_UPDATED_BY is '最后跟新人';
comment on column CONFIG_AFTER_DEAL.LAST_UPDATED_DATE is '最后更新时间';
comment on column CONFIG_AFTER_DEAL.DELETED_BY is '删除人';
comment on column CONFIG_AFTER_DEAL.DELETED_DATE is '删除时间';
comment on column CONFIG_AFTER_DEAL.IS_DELETED is '是否删除，0为删除，1已经产出';

create table WMS_ACCOUNT_ADDITION
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_ACCOUNT_ADDITION primary key,
    ACCOUNT_CODE                 VARCHAR2(32),
    BAR_CODE                     VARCHAR2(64),
    STORAGE_DATE                 VARCHAR2(32),
    SERIAL_NUMBER                VARCHAR2(64),
    MANUFACTURER                 VARCHAR2(64),
    PRODUCTION_INFO              VARCHAR2(255),
    PRODUCTION_CODE_INFO         VARCHAR2(64)
);

comment on table WMS_ACCOUNT_ADDITION is '后处理配置';
comment on column WMS_ACCOUNT_ADDITION.ID is '表id';
comment on column WMS_ACCOUNT_ADDITION.ACCOUNT_CODE  is '台账编码，自动生成';
comment on column WMS_ACCOUNT_ADDITION.BAR_CODE is '条码';
comment on column WMS_ACCOUNT_ADDITION.STORAGE_DATE is '封存日期';
comment on column WMS_ACCOUNT_ADDITION.SERIAL_NUMBER is '成品序列号';
comment on column WMS_ACCOUNT_ADDITION.MANUFACTURER is '成品序列号';
comment on column WMS_ACCOUNT_ADDITION.PRODUCTION_INFO is '产品信息';
comment on column WMS_ACCOUNT_ADDITION.PRODUCTION_CODE_INFO is '物品码';