create table WMS_AUTO_PRODUCTION_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_AUTO_PRODUCTION_INFO primary key,
    NAME           VARCHAR2(32),
    PRO_CODE       VARCHAR2(32),
    SPECIFICATIONS VARCHAR2(32),
    MODEL          VARCHAR2(32),
    DRAW_CODE      VARCHAR2(32),
    MATERIAL       VARCHAR2(32),
    INTROUDUCE     VARCHAR2(255),
    UNIT           VARCHAR2(8),
    CATEGORY_CODE  VARCHAR2(16),
    WEIGHT         NUMBER(16),
    LENGTH         NUMBER(8),
    WIDTH          NUMBER(8),
    HEIGHT         NUMBER(8),
    ATTRIBUTE1     VARCHAR2(64),
    ATTRIBUTE2     VARCHAR2(64),
    ATTRIBUTE3     VARCHAR2(64),
    ATTRIBUTE4     VARCHAR2(64),
    ATTRIBUTE5     VARCHAR2(64)
);
comment on table WMS_AUTO_PRODUCTION_INFO is '向自动仓同步的物料分类';

create table WMS_AUTO_PRODUCTION_CATEGORY
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_AUTO_PRODUCTION_CATEGORY primary key,
    CATEGORY_CODE VARCHAR2(16),
    FATHER_CODE   VARCHAR2(16),
    NAME          VARCHAR2(32),
    DETAILS       VARCHAR2(255)
);

comment on table WMS_AUTO_PRODUCTION_CATEGORY is '向自动仓同步的物料分类';

create table WMS_AUTO_OUT_STORAGE_ORDER
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_AUTO_OUT_STORAGE_ORDER primary key,
    ORDER_CODE       VARCHAR2(32),
    ORDER_ORI_CODE  VARCHAR2(32),
    WH_CODE         VARCHAR2(32),
    PRO_CODE        VARCHAR2(16),
    QUANTITY        NUMBER(32, 4),
    UNIT            VARCHAR2(16),
    LOCATION_CODE   VARCHAR2(16),
    PRIORITY        NUMBER,
    OUT_PERSON_CODE VARCHAR2(32),
    GEN_DATA        VARCHAR2(32),
    EXPIRE_DATA     VARCHAR2(64),
    QUALITY_STATUS  VARCHAR2(16),
    PROJECT_CODE    VARCHAR2(64),
    BATCH           VARCHAR2(64),
    SPLYSOT_CODE    VARCHAR2(200),
    AIRCRAFT_CODE   VARCHAR2(64),
    SORITE_CODE     VARCHAR2(64),
    STATUS          VARCHAR2(32),
    ATTRIBUTE1      VARCHAR2(64),
    ATTRIBUTE2      VARCHAR2(64),
    ATTRIBUTE3      VARCHAR2(64),
    ATTRIBUTE4      VARCHAR2(64),
    ATTRIBUTE5      VARCHAR2(64),
    ATTRIBUTE6      VARCHAR2(64),
    ATTRIBUTE7      VARCHAR2(64),
    ATTRIBUTE8      VARCHAR2(64),
    ATTRIBUTE9      VARCHAR2(64),
    ATTRIBUTE10     VARCHAR2(64)
);

comment on table WMS_AUTO_OUT_STORAGE_ORDER is '自动仓推送出库单据';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ORDER_CODE is '单据编号';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ORDER_ORI_CODE is '原始单据编号，批次属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.WH_CODE is '库房编码';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.PRO_CODE is '物料编号';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.QUANTITY is '数量';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.UNIT is '物料主单位';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.LOCATION_CODE is '建议仓位';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.PRIORITY is '优先级1-10';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.OUT_PERSON_CODE is '出库人识别标识';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.GEN_DATA is '生产日期';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.EXPIRE_DATA is '失效日期';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.QUALITY_STATUS is '质检状态';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.PROJECT_CODE is '项目编码';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.BATCH is '批次';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.SPLYSOT_CODE is '炉批号';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.AIRCRAFT_CODE is '机型';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.SORITE_CODE is '架次';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.STATUS is '状态';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE1 is '自定义属性，批次属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE2 is '自定义属性 02，批次属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE3 is '自定义属性 03，批次属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE4 is '自定义属性 04，批次属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE5 is '自定义属性 05，批次属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE6 is '自定义属性 06';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE7 is '自定义属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE8 is '自定义属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE9 is '自定义属性';
comment on column WMS_AUTO_OUT_STORAGE_ORDER.ATTRIBUTE10 is '自定义属性';

create table WMS_AUTO_IN_STORAGE_ORDER
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_AUTO_IN_STORAGE_ORDER primary key,
    ORDER_CODE        VARCHAR2(32),
    ORDER_ORI_CODE   VARCHAR2(32),
    WH_CODE          VARCHAR2(32),
    PRO_CODE         VARCHAR2(16),
    QUANTITY         NUMBER(32, 4),
    UNIT             VARCHAR2(16),
    LOCATION_CODE    VARCHAR2(16),
    PRIORITY         NUMBER(38),
    INTO_PERSON_CODE VARCHAR2(32),
    GEN_DATA         VARCHAR2(32),
    EXPIRE_DATA      VARCHAR2(64),
    QUALITY_STATUS   VARCHAR2(16),
    PROJECT_CODE     VARCHAR2(64),
    BATCH            VARCHAR2(64),
    SPLYSOT_CODE     VARCHAR2(200),
    AIRCRAFT_CODE    VARCHAR2(64),
    SORITE_CODE      VARCHAR2(64),
    STATUS          VARCHAR2(32),
    ATTRIBUTE1       VARCHAR2(64),
    ATTRIBUTE2       VARCHAR2(64),
    ATTRIBUTE3       VARCHAR2(64),
    ATTRIBUTE4       VARCHAR2(64),
    ATTRIBUTE5       VARCHAR2(64),
    ATTRIBUTE6       VARCHAR2(64),
    ATTRIBUTE7       VARCHAR2(64),
    ATTRIBUTE8       VARCHAR2(64),
    ATTRIBUTE9       VARCHAR2(64),
    ATTRIBUTE10      VARCHAR2(64)
);

comment on table WMS_AUTO_IN_STORAGE_ORDER is '自动仓推送入库单据';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ORDER_CODE is '单据编号';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ORDER_ORI_CODE is '原始单据编号，批次属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.WH_CODE is '库房编码';
comment on column WMS_AUTO_IN_STORAGE_ORDER.PRO_CODE is '物料编号';
comment on column WMS_AUTO_IN_STORAGE_ORDER.QUANTITY is '数量';
comment on column WMS_AUTO_IN_STORAGE_ORDER.UNIT is '物料主单位';
comment on column WMS_AUTO_IN_STORAGE_ORDER.LOCATION_CODE is '建议仓位';
comment on column WMS_AUTO_IN_STORAGE_ORDER.PRIORITY is '优先级1-10';
comment on column WMS_AUTO_IN_STORAGE_ORDER.INTO_PERSON_CODE is '入库人识别标识';
comment on column WMS_AUTO_IN_STORAGE_ORDER.GEN_DATA is '生产日期';
comment on column WMS_AUTO_IN_STORAGE_ORDER.EXPIRE_DATA is '失效日期';
comment on column WMS_AUTO_IN_STORAGE_ORDER.QUALITY_STATUS is '质检状态';
comment on column WMS_AUTO_IN_STORAGE_ORDER.PROJECT_CODE is '项目编码';
comment on column WMS_AUTO_IN_STORAGE_ORDER.BATCH is '批次';
comment on column WMS_AUTO_IN_STORAGE_ORDER.SPLYSOT_CODE is '炉批号';
comment on column WMS_AUTO_IN_STORAGE_ORDER.AIRCRAFT_CODE is '机型';
comment on column WMS_AUTO_IN_STORAGE_ORDER.SORITE_CODE is '架次';
comment on column WMS_AUTO_IN_STORAGE_ORDER.STATUS is '状态';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE1 is '自定义属性，批次属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE2 is '自定义属性 02，批次属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE3 is '自定义属性 03，批次属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE4 is '自定义属性 04，批次属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE5 is '自定义属性 05，批次属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE6 is '自定义属性 06';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE7 is '自定义属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE8 is '自定义属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE9 is '自定义属性';
comment on column WMS_AUTO_IN_STORAGE_ORDER.ATTRIBUTE10 is '自定义属性';

create table WMS_AUTO_IN_CERTIFICATE
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_AUTO_IN_CERTIFICATE primary key,
    RUNNING_ACCOUNT_ID VARCHAR2(32),
    ORDER_CODE          VARCHAR2(32),
    ORDER_ORI_CODE     VARCHAR2(32),
    WH_CODE            VARCHAR2(32),
    PRO_CODE           VARCHAR2(16),
    QUANTITY           NUMBER(32, 4),
    UNIT               VARCHAR2(16),
    LOCATION_CODE      VARCHAR2(16),
    PRIORITY           NUMBER,
    INTO_PERSON_CODE   VARCHAR2(32),
    CONTROL_PERSON     VARCHAR2(32),
    GEN_DATA           VARCHAR2(32),
    EXPIRE_DATA        VARCHAR2(64),
    QUALITY_STATUS     VARCHAR2(16),
    PROJECT_CODE       VARCHAR2(64),
    BATCH              VARCHAR2(64),
    SPLYSOT_CODE       VARCHAR2(200),
    AIRCRAFT_CODE      VARCHAR2(64),
    SORITE_CODE        VARCHAR2(64),
    STATUS             VARCHAR2(32),
    ATTRIBUTE1         VARCHAR2(64),
    ATTRIBUTE2         VARCHAR2(64),
    ATTRIBUTE3         VARCHAR2(64),
    ATTRIBUTE4         VARCHAR2(64),
    ATTRIBUTE5         VARCHAR2(64)
);

comment on table WMS_AUTO_IN_CERTIFICATE is '入库过账';
comment on column WMS_AUTO_IN_CERTIFICATE.ORDER_CODE is '单据编号';
comment on column WMS_AUTO_IN_CERTIFICATE.RUNNING_ACCOUNT_ID is  '流水编号';
comment on column WMS_AUTO_IN_CERTIFICATE.ORDER_ORI_CODE is '原始单据编号，批次属性';
comment on column WMS_AUTO_IN_CERTIFICATE.WH_CODE is '库房编码';
comment on column WMS_AUTO_IN_CERTIFICATE.PRO_CODE is '物料编号';
comment on column WMS_AUTO_IN_CERTIFICATE.QUANTITY is '数量';
comment on column WMS_AUTO_IN_CERTIFICATE.UNIT is '物料主单位';
comment on column WMS_AUTO_IN_CERTIFICATE.LOCATION_CODE is '建议仓位';
comment on column WMS_AUTO_IN_CERTIFICATE.INTO_PERSON_CODE is '入库人识别标识';
comment on column WMS_AUTO_IN_CERTIFICATE.CONTROL_PERSON is '操作人';
comment on column WMS_AUTO_IN_CERTIFICATE.GEN_DATA is '生产日期';
comment on column WMS_AUTO_IN_CERTIFICATE.EXPIRE_DATA is '失效日期';
comment on column WMS_AUTO_IN_CERTIFICATE.QUALITY_STATUS is '质检状态';
comment on column WMS_AUTO_IN_CERTIFICATE.PROJECT_CODE is '项目编码';
comment on column WMS_AUTO_IN_CERTIFICATE.BATCH is '批次';
comment on column WMS_AUTO_IN_CERTIFICATE.SPLYSOT_CODE is '炉批号';
comment on column WMS_AUTO_IN_CERTIFICATE.AIRCRAFT_CODE is '机型';
comment on column WMS_AUTO_IN_CERTIFICATE.SORITE_CODE is '架次';
comment on column WMS_AUTO_IN_CERTIFICATE.ATTRIBUTE1 is '自定义属性，批次属性';
comment on column WMS_AUTO_IN_CERTIFICATE.ATTRIBUTE2 is '自定义属性 02，批次属性';
comment on column WMS_AUTO_IN_CERTIFICATE.ATTRIBUTE3 is '自定义属性 03，批次属性';
comment on column WMS_AUTO_IN_CERTIFICATE.ATTRIBUTE4 is '自定义属性 04，批次属性';
comment on column WMS_AUTO_IN_CERTIFICATE.ATTRIBUTE5 is '自定义属性 05，批次属性';
comment on column WMS_AUTO_IN_CERTIFICATE.STATUS is '状态';

create table WMS_AUTO_OUT_CERTIFICATE
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_AUTO_OUT_CERTIFICATE primary key,
    RUNNING_ACCOUNT_ID VARCHAR2(32),
    ORDER_CODE          VARCHAR2(32),
    ORDER_ORI_CODE     VARCHAR2(32),
    WH_CODE            VARCHAR2(32),
    PRO_CODE           VARCHAR2(16),
    QUANTITY           NUMBER(32, 4),
    UNIT               VARCHAR2(16),
    LOCATION_CODE      VARCHAR2(16),
    OUT_PERSON_CODE   VARCHAR2(32),
    CONTROL_PERSON     VARCHAR2(32),
    GEN_DATA           VARCHAR2(32),
    EXPIRE_DATA        VARCHAR2(64),
    QUALITY_STATUS     VARCHAR2(16),
    PROJECT_CODE       VARCHAR2(64),
    BATCH              VARCHAR2(64),
    SPLYSOT_CODE       VARCHAR2(200),
    AIRCRAFT_CODE      VARCHAR2(64),
    SORITE_CODE        VARCHAR2(64),
    STATUS             VARCHAR2(32),
    ATTRIBUTE1         VARCHAR2(64),
    ATTRIBUTE2         VARCHAR2(64),
    ATTRIBUTE3         VARCHAR2(64),
    ATTRIBUTE4         VARCHAR2(64),
    ATTRIBUTE5         VARCHAR2(64)
);

comment on table WMS_AUTO_OUT_CERTIFICATE is '出库过账';
comment on column WMS_AUTO_OUT_CERTIFICATE.ORDER_CODE is '单据编号';
comment on column WMS_AUTO_OUT_CERTIFICATE.RUNNING_ACCOUNT_ID is  '流水编号';
comment on column WMS_AUTO_OUT_CERTIFICATE.ORDER_ORI_CODE is '原始单据编号，批次属性';
comment on column WMS_AUTO_OUT_CERTIFICATE.WH_CODE is '库房编码';
comment on column WMS_AUTO_OUT_CERTIFICATE.PRO_CODE is '物料编号';
comment on column WMS_AUTO_OUT_CERTIFICATE.QUANTITY is '数量';
comment on column WMS_AUTO_OUT_CERTIFICATE.UNIT is '物料主单位';
comment on column WMS_AUTO_OUT_CERTIFICATE.LOCATION_CODE is '建议仓位';
comment on column WMS_AUTO_OUT_CERTIFICATE.OUT_PERSON_CODE is '出库人识别标识';
comment on column WMS_AUTO_OUT_CERTIFICATE.CONTROL_PERSON is '操作人';
comment on column WMS_AUTO_OUT_CERTIFICATE.GEN_DATA is '生产日期';
comment on column WMS_AUTO_OUT_CERTIFICATE.EXPIRE_DATA is '失效日期';
comment on column WMS_AUTO_OUT_CERTIFICATE.QUALITY_STATUS is '质检状态';
comment on column WMS_AUTO_OUT_CERTIFICATE.PROJECT_CODE is '项目编码';
comment on column WMS_AUTO_OUT_CERTIFICATE.BATCH is '批次';
comment on column WMS_AUTO_OUT_CERTIFICATE.SPLYSOT_CODE is '炉批号';
comment on column WMS_AUTO_OUT_CERTIFICATE.AIRCRAFT_CODE is '机型';
comment on column WMS_AUTO_OUT_CERTIFICATE.SORITE_CODE is '架次';
comment on column WMS_AUTO_OUT_CERTIFICATE.ATTRIBUTE1 is '自定义属性，批次属性';
comment on column WMS_AUTO_OUT_CERTIFICATE.ATTRIBUTE2 is '自定义属性 02，批次属性';
comment on column WMS_AUTO_OUT_CERTIFICATE.ATTRIBUTE3 is '自定义属性 03，批次属性';
comment on column WMS_AUTO_OUT_CERTIFICATE.ATTRIBUTE4 is '自定义属性 04，批次属性';
comment on column WMS_AUTO_OUT_CERTIFICATE.ATTRIBUTE5 is '自定义属性 05，批次属性';
comment on column WMS_AUTO_OUT_CERTIFICATE.STATUS is '状态';

create table WMS_AUTO_REQUEST_ORDER
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint WMS_WMS_AUTO_REQUEST_ORDER primary key,
    DEAL_CODE          VARCHAR2(32),
    REQUEST_CODE       VARCHAR2(32),
    DEAL_TYPE          VARCHAR2(16),
    FROM_SYS           VARCHAR2(32),
    TO_SYS             VARCHAR2(32),
    STATUS             VARCHAR2(8)
);
comment on table WMS_AUTO_REQUEST_ORDER is '处理记录表';
comment on column WMS_AUTO_REQUEST_ORDER.DEAL_CODE is '处理编号';
comment on column WMS_AUTO_REQUEST_ORDER.REQUEST_CODE is  '请求编号';
comment on column WMS_AUTO_REQUEST_ORDER.DEAL_TYPE is '处理类型';
comment on column WMS_AUTO_REQUEST_ORDER.FROM_SYS is '来源';
comment on column WMS_AUTO_REQUEST_ORDER.TO_SYS is '去向';
comment on column WMS_AUTO_REQUEST_ORDER.STATUS is '状态';

create table WMS_AUTO_NETWORK_CONFIRM
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_AUTO_NETWORK_CONFIRM primary key,
    DEAL_CODE          VARCHAR2(32),
    REQUEST_CODE       VARCHAR2(32),
    DEAL_TYPE          VARCHAR2(16),
    FROM_SYS           VARCHAR2(32),
    TO_SYS             VARCHAR2(32),
    message            VARCHAR2(4000),
    STATUS             VARCHAR2(8)
);
comment on table WMS_AUTO_REQUEST_ORDER is '出库过账';
comment on column WMS_AUTO_REQUEST_ORDER.DEAL_CODE is '处理编号';
comment on column WMS_AUTO_REQUEST_ORDER.REQUEST_CODE is  '请求编号';
comment on column WMS_AUTO_REQUEST_ORDER.DEAL_TYPE is '处理类型';
comment on column WMS_AUTO_REQUEST_ORDER.FROM_SYS is '来源';
comment on column WMS_AUTO_REQUEST_ORDER.TO_SYS is '去向';
comment on column WMS_AUTO_REQUEST_ORDER.STATUS is '状态';