
//废弃
create table CONFIG_MOVE_WAREHOUSE
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint CONFIG_MOVE_WAREHOUSE primary key,
    CONFIG_CODE     VARCHAR2(32) not null,
    MOVEOUT_WAREHOUSE_CODE         VARCHAR2(32) not null,
    MOVEIN_WAREHOUSE_CODE         VARCHAR2(32) not null,
    NEED_QUALITY      VARCHAR2(16),
    STATUS             VARCHAR2(16),
    CREATED_BY         VARCHAR2(32) not null,
    CREATION_DATE      DATE         not null,
    LAST_UPDATED_BY    VARCHAR2(32) not null,
    LAST_UPDATE_DATE   DATE         not null,
    VERSION            VARCHAR(32)
);

comment on table CONFIG_MOVE_WAREHOUSE is '移库配置表';
comment on column CONFIG_MOVE_WAREHOUSE.ID is '表id';
comment on column CONFIG_MOVE_WAREHOUSE.CONFIG_CODE is '配置编号';
comment on column CONFIG_MOVE_WAREHOUSE.MOVEOUT_WAREHOUSE_CODE is '移出库房编码';
comment on column CONFIG_MOVE_WAREHOUSE.MOVEIN_WAREHOUSE_CODE is '移入物料编码';
comment on column CONFIG_MOVE_WAREHOUSE.NEED_QUALITY is '是否需要质检';
comment on column CONFIG_MOVE_WAREHOUSE.STATUS is '状态';
comment on column CONFIG_MOVE_WAREHOUSE.CREATED_BY is '创建人';
comment on column CONFIG_MOVE_WAREHOUSE.CREATION_DATE is '创建时间';
comment on column CONFIG_MOVE_WAREHOUSE.LAST_UPDATED_BY is '最后更新人';
comment on column CONFIG_MOVE_WAREHOUSE.LAST_UPDATE_DATE is '最后更新时间';
comment on column CONFIG_MOVE_WAREHOUSE.VERSION is '版本';

create table CONFIG_MOVE_SPEC_WAREHOUSE
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint CONFIG_MOVE_SPEC_WAREHOUSE primary key,
    CONFIG_CODE     VARCHAR2(32) not null,
    PROEUCTION_CODE  VARCHAR2(32),
    MOVEOUT_WAREHOUSE_CODE         VARCHAR2(32) not null,
    MOVEIN_WAREHOUSE_CODE         VARCHAR2(32) not null,
    NEED_QUALITY      VARCHAR2(16),
    STATUS             VARCHAR2(16),
    CREATED_BY         VARCHAR2(32) not null,
    CREATION_DATE      DATE         not null,
    LAST_UPDATED_BY    VARCHAR2(32) not null,
    LAST_UPDATE_DATE   DATE         not null,
    VERSION            VARCHAR(32)
);

comment on table CONFIG_MOVE_SPEC_WAREHOUSE is '特殊移库配置表';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.ID is '表id';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.CONFIG_CODE is '配置编号';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.PROEUCTION_CODE is '物料编码';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.MOVEOUT_WAREHOUSE_CODE is '移出库房编码';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.MOVEIN_WAREHOUSE_CODE is '移入物料编码';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.NEED_QUALITY is '是否需要质检';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.STATUS is '状态';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.CREATED_BY is '创建人';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.CREATION_DATE is '创建时间';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.LAST_UPDATED_BY is '最后更新人';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.LAST_UPDATE_DATE is '最后更新时间';
comment on column CONFIG_MOVE_SPEC_WAREHOUSE.VERSION is '版本';