create table WMS_PRODUCTION_UNIT_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_UNIT_INFO primary key,
    NAME          VARCHAR2(32) not null,
    UNIT_CODE VARCHAR2(32) not null,
    UNIT_TYPE   VARCHAR2(32),
    UNIT_STATE VARCHAR2(8) DEFAULT 'ok',
    VERSION       VARCHAR2(8),
    CREATE_USER VARCHAR(32),
    CREATE_DATA DATE DEFAULT SYSDATE
);

comment on table WMS_PRODUCTION_UNIT_INFO is '物料基础单位';
comment on column WMS_PRODUCTION_UNIT_INFO.NAME is '基础单位名称';
comment on column WMS_PRODUCTION_UNIT_INFO.UNIT_CODE is '基础单位类别';
comment on column WMS_PRODUCTION_UNIT_INFO.UNIT_STATE is '基础单位状态';
comment on column WMS_PRODUCTION_UNIT_INFO.VERSION is '版本号';
comment on column WMS_PRODUCTION_UNIT_INFO.CREATE_USER is '创建人';
comment on column WMS_PRODUCTION_UNIT_INFO.CREATE_DATA is '创建时间';

create table WMS_PRODUCTION_CATEGORY_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_CATEGORY_INFO primary key,
    NAME          VARCHAR2(32) not null,
    CATEGORY_CODE VARCHAR2(32) not null,
    FATHER_CODE   VARCHAR2(32) ,
    CATEGORY_STATE VARCHAR2(8) DEFAULT 'ok',
    VERSION       VARCHAR2(8),
    CATEGORY_SEQUENCE NUMBER(8),
    CREATE_USER VARCHAR(32),
    CREATE_DATA DATE DEFAULT SYSDATE,
    DETAILS VARCHAR2(255)
);

comment on table WMS_PRODUCTION_CATEGORY_INFO is '物料分类';
comment on column WMS_PRODUCTION_CATEGORY_INFO.NAME is '分类名称';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CATEGORY_CODE is '分类编码';
comment on column WMS_PRODUCTION_CATEGORY_INFO.FATHER_CATEGORY_CODE is '分类编码';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CATEGORY_STATE is '状态';
comment on column WMS_PRODUCTION_CATEGORY_INFO.VERSION is '版本号';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CATEGORY_SEQUENCE is '排序';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CREATE_USER is '创建人';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CREATE_DATA is '创建时间';
comment on column WMS_PRODUCTION_CATEGORY_INFO.DETAILS is '描述';

create table WMS_PRODUCTION_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_INFO primary key,
    CN_NAME       VARCHAR2(32),
    UN_NAME       VARCHAR2(32),
    PRODUCTION_CODE VARCHAR2(32) not null,
    PRODUCTION_STATE VARCHAR2(8) DEFAULT 'ok',
    CATEGORY_TYPE_CODE VARCHAR2(32),
    PRODUCTION_TYPE VARCHAR2(32),
    UNIT          VARCHAR2(32),
    WEIGHT        NUMBER(32,4) DEFAULT 0,
    WEIGHT_UNIT   VARCHAR2(32),
    PRICE         NUMBER(32,4) DEFAULT 0,
    PRODUCTION_VERSION VARCHAR2(255),
    SPEC          VARCHAR2(255),
    MARQUE        VARCHAR2(32)，
    DRAW_CODE  VARCHAR2(255),
    DETAILS       VARCHAR2(255),
    VERSION       VARCHAR2(8)
);

comment on table WMS_PRODUCTION_INFO is '物料基础信息表';
comment on column WMS_PRODUCTION_INFO.CN_NAME is '中文名称';
comment on column WMS_PRODUCTION_INFO.UN_NAME is '英文名称';
comment on column WMS_PRODUCTION_INFO.PRODUCTION_CODE is '物料编码';
comment on column WMS_PRODUCTION_INFO.PRODUCTION_STATE is '物料状态';
comment on column WMS_PRODUCTION_INFO.CATEGORY_TYPE_CODE is '物料分类';
comment on column WMS_PRODUCTION_INFO.PRODUCTION_TYPE is '物料类型，如标准件、原材料、成品等';
comment on column WMS_PRODUCTION_INFO.SPEC is '规格';
comment on column WMS_PRODUCTION_INFO.DRAW_CODE is '图号';
comment on column WMS_PRODUCTION_INFO.MARQUE is '牌号，指国家标准规定的或供应商提供的商品型号';
comment on column WMS_PRODUCTION_INFO.UNIT is '物料主单位';
comment on column WMS_PRODUCTION_INFO.PRICE is '计划价';
comment on column WMS_PRODUCTION_INFO.WEIGHT is '毛重';
comment on column WMS_PRODUCTION_INFO.WEIGHT_UNIT is '重量单位';
comment on column WMS_PRODUCTION_INFO.DETAILS is '描述';
comment on column WMS_PRODUCTION_INFO.VERSION is '版本号';

create index WMS_PRODUCTION_INFO_PRODUCTION_CODE on WMS_PRODUCTION_INFO (PRODUCTION_CODE);

create table WMS_PRODUCTION_SOURCE
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_COURDE primary key,
    PRODUCTION_CODE VARCHAR2(32) not null,
    SOURCE_TYPE VARCHAR2(8),
    VENDOR_CODE VARCHAR2(32),
    CHK_HR_DEPT_ID          VARCHAR2(32),
    FIX_HR_DEPT_ID          VARCHAR2(32),
    DEPT_ID                 VARCHAR2(32),
    IDESIGN_DEPT_ID         VARCHAR2(32),
    MANUFACTURE_FACTORY     VARCHAR2(255),
    VERSION       VARCHAR2(8)
);

comment on column WMS_PRODUCTION_SOURCE.SOURCE_TYPE is '来源类型, 0、自制，1、OEM，2、协作，3、采购，4、自用，5、非制造件,说明项目来于购买或自制以及自制的程度';
comment on column WMS_PRODUCTION_SOURCE.CHK_HR_DEPT_ID is '检验部门,HR_DEPT的主键id';
comment on column WMS_PRODUCTION_SOURCE.FIX_HR_DEPT_ID is '维修部门,HR_DEPT的主键id';
comment on column WMS_PRODUCTION_SOURCE.DEPT_ID is '承制部门';
comment on column WMS_PRODUCTION_SOURCE.IDESIGN_DEPT_ID is '设计部门';
comment on column WMS_PRODUCTION_SOURCE.MANUFACTURE_FACTORY is '生产厂商';

create table WMS_PRODUCTION_UNIT
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_UNIT primary key,
    PRODUCTION_CODE VARCHAR2(32) not null,
    UNIT  VARCHAR2(32),
    SPLY_UNIT   VARCHAR2(32),
    SPLY_STORE_UNIT_QUOTIENT NUMBER(20, 7),
    VERSION       VARCHAR2(8)
);

comment on table WMS_PRODUCTION_UNIT is '物料单位';
comment on column WMS_PRODUCTION_UNIT.SPLY_UNIT is '采购单位(正在使用)';
comment on column WMS_PRODUCTION_UNIT.SPLY_STORE_UNIT_QUOTIENT is '采购/库存单位折算系数(正在使用)';

create table WMS_PRODUCTION_PROJECT
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_PROJECT primary key,
    PRODUCTION_CODE VARCHAR2(32) not null,
    PROCECT_CODE  VARCHAR2(32),
    VERSION       VARCHAR2(8)
);

comment on table WMS_PRODUCTION_PROJECT is '物料项目';
comment on column WMS_PRODUCTION_PROJECT.PRODUCTION_CODE is '物料编码';
comment on column WMS_PRODUCTION_PROJECT.PROCECT_CODE is '项目编码'

create table WMS_PRODUCTION_KEEP_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_KEEP_INFO primary key,
    PRODUCTION_CODE VARCHAR2(32) not null,
    CONSIGNMENT_METERIAL_FLAG VARCHAR2(8),
    ABC_CODE    VARCHAR2(8),
    SAFETY_STOCK NUMBER(20,4),
    MIN_STOCK_QTY  NUMBER(20,4),
    MAX_STOCK_QTY NUMBER(20,4),
    STORAGE_LT    NUMBER(20, 7),
    ALLOW_OVERSTOCK_PERIOD NUMBER(10),
    TOOL_HIGH_WASTE_FLAG VARCHAR2(8),
    INV_PROPERTY_CODE  VARCHAR2(8),
    INV_OUT_PRINCIPLE  VARCHAR2(8),
    HEAT_TREATMENT     VARCHAR2(64),
    VERSION     VARCHAR2(8)
);

comment on table WMS_PRODUCTION_KEEP_INFO is '保管信息';
comment on column WMS_PRODUCTION_KEEP_INFO.CONSIGNMENT_METERIAL_FLAG is '寄售标记';
comment on column WMS_PRODUCTION_KEEP_INFO.ABC_CODE is 'ABC CODE，A、B、C';
comment on column WMS_PRODUCTION_KEEP_INFO.SAFETY_STOCK is '安全库存量(SAFETY STOCK)';
comment on column WMS_PRODUCTION_KEEP_INFO.MIN_STOCK_QTY is '最小库存量';
comment on column WMS_PRODUCTION_KEEP_INFO.MAX_STOCK_QTY is '最大库存量';
comment on column WMS_PRODUCTION_KEEP_INFO.TOOL_HIGH_WASTE_FLAG is '是否易耗品';
comment on column WMS_PRODUCTION_KEEP_INFO.INV_PROPERTY_CODE is '保管特征码 ^ 1-无要求 2-易变形 3-防锈不油封 4-油封 5-配钻';
comment on column WMS_PRODUCTION_KEEP_INFO.STORAGE_LT is '保证期，国内标准件用，记录供应商提供的保证期、质保期';
comment on column WMS_PRODUCTION_KEEP_INFO.INV_OUT_PRINCIPLE is '出入库原则：先入先出，后入先出，批次优先';
comment on column WMS_PRODUCTION_KEEP_INFO.HEAT_TREATMENT is '热处理要求';
comment on column WMS_PRODUCTION_KEEP_INFO.ALLOW_OVERSTOCK_PERIOD is '准许积压期限（天）'

create table WMS_PRODUCTION_SIZE_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_SIZE_INFO primary key,
    MATERIAL_THICKNESS   NUMBER(20, 7),
    MATERIAL_LENGTH       NUMBER(20, 7),
    MATERIAL_WIDTH       NUMBER(20, 7),
    MATERIAL_HEIGH       NUMBER(20, 7),
    MATERIAL_DIAMETER    NUMBER(20, 7),
    MATERIAL_WALL    NUMBER(20, 7),
    SIZE_MDS_UNIT_ID VARCHAR2(16),
    VERSION     VARCHAR2(8)
);

comment on table WMS_PRODUCTION_SIZE_INFO is '物料尺寸';
comment on column WMS_PRODUCTION_SIZE_INFO.MATERIAL_THICKNESS is '板厚';
comment on column WMS_PRODUCTION_SIZE_INFO.MATERIAL_LENGTH is '长';
comment on column WMS_PRODUCTION_SIZE_INFO.MATERIAL_WIDTH is '宽';
comment on column WMS_PRODUCTION_SIZE_INFO.MATERIAL_HEIGH is '高';
comment on column WMS_PRODUCTION_SIZE_INFO.MATERIAL_DIAMETER is '直径（棒）外径（管）';
comment on column WMS_PRODUCTION_SIZE_INFO.MATERIAL_WALL is '壁厚';
comment on column WMS_PRODUCTION_SIZE_INFO.SIZE_MDS_UNIT_ID is '尺寸计量单位';

create table WMS_THREE_PERIOD
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_THREE_PERIOD primary key,
    THREE_PERIOD_CODE        VARCHAR2(32) not null,
    ENVELOP_CODE                 VARCHAR2(32) not null,
    BASIC_EFFECT_STOCK_PERIOD    NUMBER,
    EFFECT_STOCK_PERIOD          NUMBER,
    FIRST_RECHECK_PERIOD         NUMBER,
    SECOND_RECHECK_PERIOD        NUMBER,
    THIRD_RECHECK_PERIOD         NUMBER,
    FIRST_RECHECK_EFFECT_PERIOD  NUMBER,
    SECOND_RECHECK_EFFECT_PERIOD NUMBER,
    THIRD_RECHECK_EFFECT_PERIOD  NUMBER,
    INFORM_IN_ADVANCE_PERIOD     NUMBER,
    USE_PERIOD                   NUMBER,
    OIL_PERIOD                   NUMBER,
    CREATED_BY                   VARCHAR2(32) not null,
    CREATION_DATE                DATE         not null,
    LAST_UPDATED_BY              VARCHAR2(32) not null,
    LAST_UPDATE_DATE             DATE         not null,
    OVERHAUL_PERIOD              NUMBER,
    GUARANTY_PERIOD              NUMBER,
    CONTROL_BASE                 VARCHAR2(32),
    FOURTH_RECHECK_PERIOD        NUMBER,
    STORAGE_PERIOD               NUMBER,
    INV_THREE_PERIOD_NAME        VARCHAR2(128),
    STORAGE_TYPE                 VARCHAR2(255),
   VERSION                       VARCHAR2(8)
);

comment on table  WMS_THREE_PERIOD is '库存三期定义表';
comment on column WMS_THREE_PERIOD.THREE_PERIOD_CODE is '库存三期代码';
comment on column WMS_THREE_PERIOD.ENVELOP_CODE is '封装方式代码 ^ 01-正常包装 02-塑压密封 03-罐装<remark>封装方式，通用代码 MDS_ENVELOP_CODE ，01金属油封， 02橡胶报废，03复验，CP成品';
comment on column WMS_THREE_PERIOD.BASIC_EFFECT_STOCK_PERIOD is '基本有效贮存期(天)<remark>基本有效贮存期(月)';
comment on column WMS_THREE_PERIOD.EFFECT_STOCK_PERIOD is '有效贮存期(天)<remark>有效贮存期(月)，库存期';
comment on column WMS_THREE_PERIOD.FIRST_RECHECK_PERIOD is '首复验期(天)<remark>第一次复验延长期(月)';
comment on column WMS_THREE_PERIOD.SECOND_RECHECK_PERIOD is '次复验期(天)<remark>第二次复验延长期(月)';
comment on column WMS_THREE_PERIOD.THIRD_RECHECK_PERIOD is '再复验期(天)<remark>第三次复验延长期(月)';
comment on column WMS_THREE_PERIOD.FIRST_RECHECK_EFFECT_PERIOD is '首复验继续有效期(天)<remark>首次复验有效期(月)'
comment on column WMS_THREE_PERIOD.SECOND_RECHECK_EFFECT_PERIOD is '次复验继续有效期(天)<remark>其次复验有效期(月)';
comment on column WMS_THREE_PERIOD.THIRD_RECHECK_EFFECT_PERIOD is '再复验继续有效期(天)<remark>再次复验有效期(月)';
comment on column WMS_THREE_PERIOD.INFORM_IN_ADVANCE_PERIOD is '提前通知期(天)<remark>提前通知期(月)';
comment on column WMS_THREE_PERIOD.USE_PERIOD is '使用期(天)<remark>使用期(月)';
comment on column WMS_THREE_PERIOD.OIL_PERIOD is '油封期(天)<remark>油封期(月)';
comment on column WMS_THREE_PERIOD.CREATED_BY is '创建人';
comment on column WMS_THREE_PERIOD.CREATION_DATE is '创建时间';
comment on column WMS_THREE_PERIOD.VERSION is '版本';
comment on column WMS_THREE_PERIOD.OVERHAUL_PERIOD is '翻修期';
comment on column WMS_THREE_PERIOD.GUARANTY_PERIOD is '保证期(天)';
comment on column WMS_THREE_PERIOD.CONTROL_BASE is '控制基准，DOM，DOS';
comment on column WMS_THREE_PERIOD.FOURTH_RECHECK_PERIOD is '第四次复验延长期(月)';
comment on column WMS_THREE_PERIOD.STORAGE_PERIOD is '保管期';
comment on column WMS_THREE_PERIOD.INV_THREE_PERIOD_NAME is '库存三期描述';
comment on column WMS_THREE_PERIOD.STORAGE_TYPE is '贮存方式';

create table WMS_TPRODUCTION_THREE_PERIOD
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_TPRODUCTION_THREE_PERIOD primary key,
    PRODUCTION_CODE VARCHAR2(32),
    THREE_PERIOD_CODE VARCHAR(32)
);

comment on table  WMS_TPRODUCTION_THREE_PERIOD is '物料三期关联关系表';