create table WMS_MATCH_BILL
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_MATCH_BILL primary key,
    BILL_CODE          VARCHAR2(32) not null,
    TARGET_CODE        VARCHAR2(32) not null,
    TARGET_TYPE        VARCHAR2(32),
    STATUS             VARCHAR2(32),
    CREATED_BY         VARCHAR2(32) not null,
    CREATION_DATE      DATE         not null,
    LAST_UPDATED_BY    VARCHAR2(32) not null,
    LAST_UPDATE_DATE   DATE         not null,
    VERSION            VARCHAR(32),
    NOTE               VARCHAR2(4000)
);

comment on table WMS_MATCH_BILL is '配套单';
comment on column WMS_MATCH_BILL.BILL_CODE is '配套单号';
comment on column WMS_MATCH_BILL.TARGET_CODE is '配套目标代码，如派工号等';
comment on column WMS_MATCH_BILL.TARGET_TYPE is '配套目标类型，如派工单等';
comment on column WMS_MATCH_BILL.STATUS is '状态';
comment on column WMS_MATCH_BILL.CREATED_BY is '创建人';
comment on column WMS_MATCH_BILL.CREATION_DATE      is '创建时间';
comment on column WMS_MATCH_BILL.LAST_UPDATED_BY    is '最后更新人';
comment on column WMS_MATCH_BILL.LAST_UPDATE_DATE   is '最后更新时间';
comment on column WMS_MATCH_BILL.VERSION   is '版本';
comment on column WMS_MATCH_BILL.NOTE   is '备注';

create table WMS_MATCH_BILL_SUB
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_MATCH_BILL_SUB primary key,
    BILL_CODE                    VARCHAR2(32) not null,
    DISPATCH_CODE                VARCHAR2(32),
    PRODUCTION_CODE              VARCHAR2(32) not null,
    WAREHOUSE_LOCATION_CODE      VARCHAR2(32),
    PRODUCTION_TYPE              VARCHAR2(16) ,
    IS_PARENT                    VARCHAR2(8) DEFAULT '2',
    PRODUCE_STATUS               VARCHAR2(16),
    PARENT_PRODUCTION_CODE       VARCHAR2(32),
    PROJECT_CODE                 VARCHAR2(32),
    BRAND                        VARCHAR2(32),
    SPECIFICATIONS               VARCHAR2(32),
    PRODUCTION_LEVEL              VARCHAR2(32),
    TECHNICAL_CONDITIONS         VARCHAR2(64),
    ADDITIONAL_TECHNICAL_CONDITIONS VARCHAR2(64),
    DRAW_CODE                    VARCHAR2(32),
    THREE_PERIOD_CODE            VARCHAR2(32),
    MANUFACTURE_DATE             DATE,
    EXPIRATION_DATE              DATE,
    BATCH                        VARCHAR2(32),
    SPLYSOT_CODE                 VARCHAR2(200),
    AIRCRAFT_CODE                VARCHAR2(64),
    SORTIE_CODE                  VARCHAR2(64),
    MODEL_CODE                   VARCHAR2(64),
    CONSTRUCTION_CODE            VARCHAR2(64),
    QUALITY_CODE                 VARCHAR2(64),
    QUALITY_STATUS               VARCHAR2(32),
    STATUS                       VARCHAR2(32),
    CERTIFICATE_NO               VARCHAR2(32),
    SUPPLY_CERTIFICATE_NO        VARCHAR2(32),
    QUANTITY                     NUMBER(32,4),
    TRY_QUANTITY                 NUMBER(32,4),
    UNIT                         VARCHAR2(32),
    RECEIVER_SYS_USER            VARCHAR2(32),
    RECEIVER_HR_DEPT             VARCHAR2(32),
    IS_CONSIGNMENT               VARCHAR2(16),
    LAST_UPDATE_BY               VARCHAR2(32) not null,
    LAST_UPDATE_DATE             DATE         not null,
    DETAILS                      VARCHAR2(200),
    ATTRIBUTE_1                  VARCHAR2(32),
    ATTRIBUTE_2                  VARCHAR2(32),
    ATTRIBUTE_3                  VARCHAR2(32),
    ATTRIBUTE_4                  VARCHAR2(32),
    ATTRIBUTE_5                  VARCHAR2(32),
    ATTRIBUTE_6                  VARCHAR2(32),
    ATTRIBUTE_7                  VARCHAR2(32),
    ATTRIBUTE_8                  VARCHAR2(32),
    ATTRIBUTE_9                  VARCHAR2(32),
    ATTRIBUTE_10                 VARCHAR2(32),
    VERSION                      VARCHAR2(32)
);

comment on table WMS_MATCH_BILL_SUB is '配套单子表';
comment on column WMS_MATCH_BILL_SUB.ID is '表id';
comment on column WMS_MATCH_BILL_SUB.DISPATCH_CODE is '派工号，FO执行序列号';
comment on column WMS_MATCH_BILL_SUB.PRODUCTION_CODE is '产品编码';
comment on column WMS_MATCH_BILL_SUB.WAREHOUSE_LOCATION_CODE  is '库位号';
comment on column WMS_MATCH_BILL_SUB.PRODUCTION_TYPE is '产品类型';
comment on column WMS_MATCH_BILL_SUB.IS_PARENT is '是否为父件，0父件、1子件、2非父子件';
comment on column WMS_MATCH_BILL_SUB.PRODUCE_STATUS is '物料制造处理状态，produce 在制品，clout 余料，waste废料';
comment on column WMS_MATCH_BILL_SUB.PARENT_PRODUCTION_CODE is '父产品编码';
comment on column WMS_MATCH_BILL_SUB.PROJECT_CODE is '项目编码';
comment on column WMS_MATCH_BILL_SUB.BRAND is '牌号';
comment on column WMS_MATCH_BILL_SUB.SPECIFICATIONS is '规格';
comment on column WMS_MATCH_BILL_SUB.PRODUCTION_LEVEL is '状态/级别/型号';
comment on column WMS_MATCH_BILL_SUB.TECHNICAL_CONDITIONS is '项目编码';
comment on column WMS_MATCH_BILL_SUB.ADDITIONAL_TECHNICAL_CONDITIONS is '附加技术条件';
comment on column WMS_MATCH_BILL_SUB.DRAW_CODE is '图号';
comment on column WMS_MATCH_BILL_SUB.THREE_PERIOD_CODE is '三期代码';
comment on column WMS_MATCH_BILL_SUB.MANUFACTURE_DATE   is '生产日期';
comment on column WMS_MATCH_BILL_SUB.EXPIRATION_DATE is '过期日期';
comment on column WMS_MATCH_BILL_SUB.BATCH           is '批次号';
comment on column WMS_MATCH_BILL_SUB.SPLYSOT_CODE    is '炉批号或小号';
comment on column WMS_MATCH_BILL_SUB.AIRCRAFT_CODE   is '机型';
comment on column WMS_MATCH_BILL_SUB.SORTIE_CODE     is '架次';
comment on column WMS_MATCH_BILL_SUB.MODEL_CODE    is '版号';
comment on column WMS_MATCH_BILL_SUB.CONSTRUCTION_CODE is '构型号';
comment on column WMS_MATCH_BILL_SUB.QUALITY_STATUS     is '质检状态';
comment on column WMS_MATCH_BILL_SUB.QUALITY_CODE     is '质量编号';
comment on column WMS_MATCH_BILL_SUB.STATUS              is '状态';
comment on column WMS_MATCH_BILL_SUB.CERTIFICATE_NO              is '合格证号';
comment on column WMS_MATCH_BILL_SUB.SUPPLY_CERTIFICATE_NO  is '供方合格证号';
comment on column WMS_MATCH_BILL_SUB.QUANTITY  is '数量';
comment on column WMS_MATCH_BILL_SUB.TRY_QUANTITY      is '试料数量';
comment on column WMS_MATCH_BILL_SUB.UNIT                  is '主单位';
comment on column WMS_MATCH_BILL_SUB.RECEIVER_SYS_USER      is '接收人';
comment on column WMS_MATCH_BILL_SUB.RECEIVER_HR_DEPT        is '接收部门';
comment on column WMS_MATCH_BILL_SUB.LAST_UPDATE_BY          is '最后更新人';
comment on column WMS_MATCH_BILL_SUB.LAST_UPDATE_DATE          is '最后更新时间';
comment on column WMS_MATCH_BILL_SUB.DETAILS                   is '备注';

create table WMS_MATCH_PRE_OUT
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_MATCH_PRE_OUT primary key,
    BILL_CODE          VARCHAR2(32) not null,
    OUT_CODE           VARCHAR2(32) not null,
    STATUS             VARCHAR2(32)
);
comment on table WMS_MATCH_PRE_OUT is '配套单与预出库单关联表';
comment on column WMS_MATCH_PRE_OUT.ID is '表id';
comment on column WMS_MATCH_PRE_OUT.BILL_CODE is '配套单号';
comment on column WMS_MATCH_PRE_OUT.OUT_CODE is '预出库单号';
comment on column WMS_MATCH_PRE_OUT.STATUS is '状态';

create table WMS_MATCH_OUT
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_MATCH_OUT primary key,
    BILL_CODE          VARCHAR2(32) not null,
    OUT_CODE           VARCHAR2(32) not null,
    STATUS             VARCHAR2(32)
);
comment on table WMS_MATCH_OUT is '配套单与出库单关联表';
comment on column WMS_MATCH_OUT.ID is '表id';
comment on column WMS_MATCH_OUT.BILL_CODE is '配套单号';
comment on column WMS_MATCH_OUT.OUT_CODE is '出库单号';
comment on column WMS_MATCH_OUT.STATUS is '状态';

create table WMS_MATCH_IN
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_MATCH_IN primary key,
    BILL_CODE          VARCHAR2(32) not null,
    IN_CODE           VARCHAR2(32) not null,
    STATUS             VARCHAR2(32)
);
comment on table WMS_MATCH_OUT is '配套单与入库单关联表';
comment on column WMS_MATCH_OUT.ID is '表id';
comment on column WMS_MATCH_OUT.BILL_CODE is '配套单号';
comment on column WMS_MATCH_OUT.OUT_CODE is '入库单号';
comment on column WMS_MATCH_OUT.STATUS is '状态';