create table WMS_MESSAGE
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_MESSAGE primary key,
    REQUEST_CODE     VARCHAR2(32) not null,
    DEAL_CODE         VARCHAR2(32) not null,
    DEAL_TYPE         VARCHAR2(32) not null,
    FROM_SYS          VARCHAR2(255),
    TO_SYS            VARCHAR2(255),
    MESSAGE           VARCHAR2(4000),
    STATUS            VARCHAR2(32),
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null
);

comment on table WMS_MESSAGE is '入库单子表';
comment on column WMS_MESSAGE.ID is '表id';
comment on column WMS_MESSAGE.REQUEST_CODE is '表id';
comment on column WMS_MESSAGE.DEAL_CODE is '处理单号';
comment on column WMS_MESSAGE.DEAL_TYPE is '处理类型';
comment on column WMS_MESSAGE.FROM_SYS is '来源系统';
comment on column WMS_MESSAGE.TO_SYS is '去向系统';
comment on column WMS_MESSAGE.MESSAGE is '消息';
comment on column WMS_MESSAGE.STATUS is '状态';
comment on column WMS_MESSAGE.CREATED_BY is '创建人';
comment on column WMS_MESSAGE.CREATED_DATE is '创建时间';
comment on column WMS_MESSAGE.LAST_UPDATED_BY is '最后跟新人';
comment on column WMS_MESSAGE.LAST_UPDATED_DATE is '最后更新时间';
comment on column WMS_MESSAGE.DELETED_BY is '删除人';
comment on column WMS_MESSAGE.DELETED_DATE is '删除时间';
comment on column WMS_MESSAGE.IS_DELETED is '是否删除，0为删除，1已经产出';