create table WMS_PRODUCTION_CATEGORY_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_CATEGORY_INFO primary key,
    NAME          VARCHAR2(32) not null,
    CATEGORY_CODE VARCHAR2(32) not null,
    FATHER_CODE   VARCHAR2(32) ,
    CATEGORY_STATE VARCHAR2(8) DEFAULT 'ok',
    VERSION       VARCHAR2(8),
    CATEGORY_SEQUENCE NUMBER(8),
    CREATE_USER VARCHAR(32),
    CREATE_DATA DATE DEFAULT SYSDATE,
    DETAILS VARCHAR2(255)
);

comment on table WMS_PRODUCTION_CATEGORY_INFO is '物料分类';
comment on column WMS_PRODUCTION_CATEGORY_INFO.NAME is '分类名称';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CATEGORY_CODE is '分类编码';
comment on column WMS_PRODUCTION_CATEGORY_INFO.FATHER_CATEGORY_CODE is '分类编码';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CATEGORY_STATE is '状态';
comment on column WMS_PRODUCTION_CATEGORY_INFO.VERSION is '版本号';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CATEGORY_SEQUENCE is '排序';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CREATE_USER is '创建人';
comment on column WMS_PRODUCTION_CATEGORY_INFO.CREATE_DATA is '创建时间';
comment on column WMS_PRODUCTION_CATEGORY_INFO.DETAILS is '描述';

create table WMS_THREE_PERIOD
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_THREE_PERIOD primary key,
    THREE_PERIOD_CODE        VARCHAR2(32) not null,
    ENVELOP_CODE                 VARCHAR2(32) not null,
    BASIC_EFFECT_STOCK_PERIOD    NUMBER,
    EFFECT_STOCK_PERIOD          NUMBER,
    FIRST_RECHECK_PERIOD         NUMBER,
    SECOND_RECHECK_PERIOD        NUMBER,
    THIRD_RECHECK_PERIOD         NUMBER,
    FIRST_RECHECK_EFFECT_PERIOD  NUMBER,
    SECOND_RECHECK_EFFECT_PERIOD NUMBER,
    THIRD_RECHECK_EFFECT_PERIOD  NUMBER,
    INFORM_IN_ADVANCE_PERIOD     NUMBER,
    USE_PERIOD                   NUMBER,
    OIL_PERIOD                   NUMBER,
    CREATED_BY                   VARCHAR2(32) not null,
    CREATION_DATE                DATE         not null,
    LAST_UPDATED_BY              VARCHAR2(32) not null,
    LAST_UPDATE_DATE             DATE         not null,
    OVERHAUL_PERIOD              NUMBER,
    GUARANTY_PERIOD              NUMBER,
    CONTROL_BASE                 VARCHAR2(32),
    FOURTH_RECHECK_PERIOD        NUMBER,
    STORAGE_PERIOD               NUMBER,
    INV_THREE_PERIOD_NAME        VARCHAR2(128),
    STORAGE_TYPE                 VARCHAR2(255),
   VERSION                       VARCHAR2(8)
);

comment on table  WMS_THREE_PERIOD is '库存三期定义表';
comment on column WMS_THREE_PERIOD.THREE_PERIOD_CODE is '库存三期代码';
comment on column WMS_THREE_PERIOD.ENVELOP_CODE is '封装方式代码 ^ 01-正常包装 02-塑压密封 03-罐装<remark>封装方式，通用代码 MDS_ENVELOP_CODE ，01金属油封， 02橡胶报废，03复验，CP成品';
comment on column WMS_THREE_PERIOD.BASIC_EFFECT_STOCK_PERIOD is '基本有效贮存期(天)<remark>基本有效贮存期(月)';
comment on column WMS_THREE_PERIOD.EFFECT_STOCK_PERIOD is '有效贮存期(天)<remark>有效贮存期(月)，库存期';
comment on column WMS_THREE_PERIOD.FIRST_RECHECK_PERIOD is '首复验期(天)<remark>第一次复验延长期(月)';
comment on column WMS_THREE_PERIOD.SECOND_RECHECK_PERIOD is '次复验期(天)<remark>第二次复验延长期(月)';
comment on column WMS_THREE_PERIOD.THIRD_RECHECK_PERIOD is '再复验期(天)<remark>第三次复验延长期(月)';
comment on column WMS_THREE_PERIOD.FIRST_RECHECK_EFFECT_PERIOD is '首复验继续有效期(天)<remark>首次复验有效期(月)'
comment on column WMS_THREE_PERIOD.SECOND_RECHECK_EFFECT_PERIOD is '次复验继续有效期(天)<remark>其次复验有效期(月)';
comment on column WMS_THREE_PERIOD.THIRD_RECHECK_EFFECT_PERIOD is '再复验继续有效期(天)<remark>再次复验有效期(月)';
comment on column WMS_THREE_PERIOD.INFORM_IN_ADVANCE_PERIOD is '提前通知期(天)<remark>提前通知期(月)';
comment on column WMS_THREE_PERIOD.USE_PERIOD is '使用期(天)<remark>使用期(月)';
comment on column WMS_THREE_PERIOD.OIL_PERIOD is '油封期(天)<remark>油封期(月)';
comment on column WMS_THREE_PERIOD.CREATED_BY is '创建人';
comment on column WMS_THREE_PERIOD.CREATION_DATE is '创建时间';
comment on column WMS_THREE_PERIOD.VERSION is '版本';
comment on column WMS_THREE_PERIOD.OVERHAUL_PERIOD is '翻修期';
comment on column WMS_THREE_PERIOD.GUARANTY_PERIOD is '保证期(天)';
comment on column WMS_THREE_PERIOD.CONTROL_BASE is '控制基准，DOM，DOS';
comment on column WMS_THREE_PERIOD.FOURTH_RECHECK_PERIOD is '第四次复验延长期(月)';
comment on column WMS_THREE_PERIOD.STORAGE_PERIOD is '保管期';
comment on column WMS_THREE_PERIOD.INV_THREE_PERIOD_NAME is '库存三期描述';
comment on column WMS_THREE_PERIOD.STORAGE_TYPE is '贮存方式';

create table WMS_TPRODUCTION_THREE_PERIOD
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_TPRODUCTION_THREE_PERIOD primary key,
    PRODUCTION_CODE VARCHAR2(32),
    THREE_PERIOD_CODE VARCHAR(32)
);

comment on table  WMS_TPRODUCTION_THREE_PERIOD is '物料三期关联关系表';

create table WMS_PRODUCTION_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_PRODUCTION_INFO primary key,
    CN_NAME       VARCHAR2(32),
    UN_NAME       VARCHAR2(32),
    PRODUCTION_CODE VARCHAR2(32) not null,
    PRODUCTION_STATE VARCHAR2(8) DEFAULT 'ok',
    CATEGORY_TYPE_CODE VARCHAR2(32),
    PRODUCTION_TYPE VARCHAR2(32),
    UNIT          VARCHAR2(32),
    BUY_UNIT      VARCHAR2(32),
    QUOTA_UNIT      VARCHAR2(32),
    BUY_CONVERSION_COEFFIENT  VARCHAR2(32),
    QUOTA_CONVERSION_COEFFIENT  VARCHAR2(32),
    WEIGHT        NUMBER(32,4) DEFAULT 0,
    WEIGHT_UNIT   VARCHAR2(32),
    MANUFACTURE_DEPT  VARCHAR2(32),
    CONSIGNMENT_METERIAL_FLAG VARCHAR2(8),
    ABC_CODE VARCHAR2(8),
    SAFETY_STOCK NUMBER(32,4),
    MIN_STOCK_QTY NUMBER(32,4),
    MAX_STOCK_QTY NUMBER(32,4),
    TOOL_HIGH_WASTE_FLAG VARCHAR2(8),
    INV_PROPERTY_CODE VARCHAR2(8),
    STORAGE_LT VARCHAR2(32),
    INV_OUT_PRINCIPLE VARCHAR2(32),
    HEAT_TREATMENT VARCHAR2(32),
    ALLOW_OVERSTOCK_PERIOD VARCHAR2(32),
    PROCESS_ROUTE VARCHAR2(32),
    PRICE_TYPE VARCHAR2(32),
    TREE_PERIOD_CODE VARCHAR2(32),
    MATERIAL_THICKNESS NUMBER(32,4),
    MATERIAL_LENGTH NUMBER(32,4),
    MATERIAL_WIDTH NUMBER(32,4),
    MATERIAL_HEIGH NUMBER(32,4),
    MATERIAL_DIAMETER NUMBER(32,4),
    MATERIAL_WALL NUMBER(32,4),
    SIZE_MDS_UNIT_ID VARCHAR2(32),
    DRAW_CODE  VARCHAR2(255),
    CONTROY_TYPE  VARCHAR2(16),
    FROM_TYPE     VARCHAR2(16),
    DETAILS       VARCHAR2(255),
    VERSION       VARCHAR2(8)
);

comment on table WMS_PRODUCTION_INFO is '物料基础信息表';
comment on column WMS_PRODUCTION_INFO.CN_NAME is '中文名称';
comment on column WMS_PRODUCTION_INFO.UN_NAME is '英文名称';
comment on column WMS_PRODUCTION_INFO.PRODUCTION_CODE is '物料编码';
comment on column WMS_PRODUCTION_INFO.PRODUCTION_STATE is '物料状态';
comment on column WMS_PRODUCTION_INFO.CATEGORY_TYPE_CODE is '物料分类';
comment on column WMS_PRODUCTION_INFO.PRODUCTION_TYPE is '物料类型，如标准件、原材料、成品等';
comment on column WMS_PRODUCTION_INFO.DRAW_CODE is '图号';
comment on column WMS_PRODUCTION_INFO.UNIT is '物料主单位';
comment on column WMS_PRODUCTION_INFO.WEIGHT is '毛重';
comment on column WMS_PRODUCTION_INFO.WEIGHT_UNIT is '重量单位';
comment on column WMS_PRODUCTION_INFO.DETAILS is '描述';
comment on column WMS_PRODUCTION_INFO.VERSION is '版本号';
comment on column WMS_PRODUCTION_INFO.BUY_UNIT is '采购单位';
comment on column WMS_PRODUCTION_INFO.QUOTA_UNIT is '定额单位';
comment on column WMS_PRODUCTION_INFO.BUY_CONVERSION_COEFFIENT is '采购单位转换系数';
comment on column WMS_PRODUCTION_INFO.QUOTA_CONVERSION_COEFFIENT is '定额单位转换系数';
comment on column WMS_PRODUCTION_INFO.CONSIGNMENT_METERIAL_FLAG is '寄售标记';
comment on column WMS_PRODUCTION_INFO.MANUFACTURE_DEPT  is '主制部门';
comment on column WMS_PRODUCTION_INFO.CONTROY_TYPE  is '管控类型';
comment on column WMS_PRODUCTION_INFO.FROM_TYPE  is '来源类型';
comment on column WMS_PRODUCTION_INFO.ABC_CODE is 'ABC编码';
comment on column WMS_PRODUCTION_INFO.SAFETY_STOCK is '安全库存量';
comment on column WMS_PRODUCTION_INFO.MIN_STOCK_QTY is '最小库存量';
comment on column WMS_PRODUCTION_INFO.MAX_STOCK_QTY is '最大库存量';
comment on column WMS_PRODUCTION_INFO.TOOL_HIGH_WASTE_FLAG is '是否易耗品';
comment on column WMS_PRODUCTION_INFO.INV_PROPERTY_CODE is '保管特征码 ^ 1-无要求 2-易变形 3-防锈不油封 4-油封 5-配钻';
comment on column WMS_PRODUCTION_INFO.INV_OUT_PRINCIPLE is '出入库原则：先入先出，后入先出，批次优先';
comment on column WMS_PRODUCTION_INFO.HEAT_TREATMENT is '热处理规则';
comment on column WMS_PRODUCTION_INFO.ALLOW_OVERSTOCK_PERIOD is '准许积压期限（天';
comment on column WMS_PRODUCTION_INFO.PROCESS_ROUTE is '工艺路线';
comment on column WMS_PRODUCTION_INFO.PRICE_TYPE is '价格类型，采购价还是计划价';
comment on column WMS_PRODUCTION_INFO.TREE_PERIOD_CODE is '三期代码';
comment on column WMS_PRODUCTION_INFO.MATERIAL_THICKNESS is '板厚';
comment on column WMS_PRODUCTION_INFO.MATERIAL_LENGTH is '长';
comment on column WMS_PRODUCTION_INFO.MATERIAL_WIDTH is '宽';
comment on column WMS_PRODUCTION_INFO.MATERIAL_HEIGH is '高';
comment on column WMS_PRODUCTION_INFO.MATERIAL_DIAMETER is '直径';
comment on column WMS_PRODUCTION_INFO.MATERIAL_WALL is '壁厚';
comment on column WMS_PRODUCTION_INFO.SIZE_MDS_UNIT_ID is '尺寸计量单位';

create table WMS_PRODUCTION_PRICE_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint WMS_PRODUCTION_PRICE_INFO primary key,
    PRODUCE_CODE          VARCHAR2(32) not null,
    PROJECT_CODE          VARCHAR2(32),
    PRICE                 NUMBER(32,4),
    STATUS                VARCHAR2(8),
    IS_DEFAULT            VARCHAR2(8)
);

comment on table WMS_PRODUCTION_PRICE_INFO is '物料价格表';
comment on column WMS_PRODUCTION_PRICE_INFO.PRODUCE_CODE is '物料编码';
comment on column WMS_PRODUCTION_PRICE_INFO.PROJECT_CODE is '项目编码';
comment on column WMS_PRODUCTION_PRICE_INFO.PRICE is '计划价';
comment on column WMS_PRODUCTION_PRICE_INFO.STATUS is '有效性';
comment on column WMS_PRODUCTION_PRICE_INFO.IS_DEFAULT is '是否默认，由于之前系统遗留问题，有很多价格是在物料上，且价格表中没有单独价格';

create table WMS_PRODUCTION_MARQUE_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint WMS_PRODUCTION_MARQUE_INFO primary key,
    PRODUCE_CODE          VARCHAR2(32) not null,
    MARQUE                VARCHAR2(32),
    SPEC                  VARCHAR2(32),
    TECH_CONDITION        VARCHAR2(32),
    GT_CODE               VARCHAR2(32),
    TYPE_AND_STATUES          VARCHAR2(32),
    IS_DEFAULT                VARCHAR2(8)
);

comment on table WMS_PRODUCTION_MARQUE_INFO is '物料牌号表';
comment on column WMS_PRODUCTION_MARQUE_INFO.PRODUCE_CODE is '物料编码';
comment on column WMS_PRODUCTION_MARQUE_INFO.MARQUE is '牌号';
comment on column WMS_PRODUCTION_MARQUE_INFO.SPEC is '规格';
comment on column WMS_PRODUCTION_MARQUE_INFO.TECH_CONDITION is '技术条件';
comment on column WMS_PRODUCTION_MARQUE_INFO.GT_CODE is '附加技术条件';
comment on column WMS_PRODUCTION_MARQUE_INFO.TYPE_AND_STATUES is '状态/型别/级别';
comment on column WMS_PRODUCTION_MARQUE_INFO.IS_DEFAULT is '是否默认，由于之前系统遗留问题';