//废弃

create table WMS_MOVE_WAREHOUSE_BILL
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_DELIVER primary key,
    MOVE_CODE     VARCHAR2(32) not null,
    OUT_WAREHOUSE_CODE         VARCHAR2(32) not null,
    IN_WAREHOUSE_CODE  VARCHAR2(32) not null,
    OUT_BILL_CODE      VARCHAR2(32),
    IN_BILL_CODE       VARCHAR2(32),
    NEED_QUALITY       VARCHAR2(16),
    STATUS             VARCHAR2(16),
    CREATED_BY         VARCHAR2(32) not null,
    CREATION_DATE      DATE         not null,
    LAST_UPDATED_BY    VARCHAR2(32) not null,
    LAST_UPDATE_DATE   DATE         not null，
    VERSION            VARCHAR(32),
    NOTE               VARCHAR2(4000)
);

comment on table WMS_MOVE_WAREHOUSE_BILL is '移库单';
comment on column WMS_MOVE_WAREHOUSE_BILL.ID is '表id';
comment on column WMS_OUT_WAREHOUSE_BILL.MOVE_CODE is '移库单号';
comment on column WMS_OUT_WAREHOUSE_BILL.OUT_WAREHOUSE_CODE is '移出库房编号';
comment on column WMS_OUT_WAREHOUSE_BILL.IN_WAREHOUSE_CODE is '移库库房号'；
comment on column WMS_OUT_WAREHOUSE_BILL.OUT_BILL_CODE is '移出库房编码'；
comment on column WMS_OUT_WAREHOUSE_BILL.IN_BILL_CODE is '移入库房编号';
comment on column WMS_OUT_WAREHOUSE_BILL.STATUS is '移库单状态';
comment on column WMS_OUT_WAREHOUSE_BILL.CREATED_BY is '创建人';
comment on column WMS_OUT_WAREHOUSE_BILL.CREATION_DATE is '创建时间';
comment on column WMS_OUT_WAREHOUSE_BILL.LAST_UPDATED_BY is '最后修改人';
comment on column WMS_OUT_WAREHOUSE_BILL.LAST_UPDATE_DATE is '最后修改时间';
comment on column WMS_OUT_WAREHOUSE_BILL.NOTE is '备注';
comment on column WMS_OUT_WAREHOUSE_BILL.VERSION is '版本';

create table WMS_MOVE_WAREHOUSE_BILL_SUB
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_DELIVER primary key,
    BILL_CODE                    VARCHAR2(32) not null,
    ACCOUNT_ID                   VARCHAR2(32),
    WAREHOUSE_LOCATION_CODE      VARCHAR2(32),
    PRODUCTION_CODE              VARCHAR2(32) not null,
    PRODUCTION_TYPE              VARCHAR2(16) ,
    IS_PARENT                    VARCHAR2(8) DEFAULT '2',
    IS_PRODUCE                   VARCHAR2(8),
    PARENT_PRODUCTION_CODE       VARCHAR2(32),
    PROJECT_CODE                 VARCHAR2(32),
    BRAND                        VARCHAR2(32),
    SPECIFICATIONS               VARCHAR2(32),
    PROUCTION_LEVEL              VARCHAR2(32),
    TECHNICAL_CONDITIONS         VARCHAR2(64),
    ADDITIONAL_TECHNICAL_CONDITIONS VARCHAR2(64),
    DRAW_CODE                    VARCHAR2(32),
    THREE_PERIOD_CODE            VARCHAR2(32),
    MANUFACTURE_DATA             DATA,
    EXPIRATION_DATA              DATA,
    BATCH                        VARCHAR2(32),
    SPLYSOT_CODE                 VARCHAR2(200),
    AIRCRAFT_CODE                VARCHAR2(64),
    SORTIE_CODE                  VARCHAR2(64),
    MODEL_CODE                   VARCHAR2(64),
    CONSTRUCTION_CODE            VARCHAR2(64),
    QUALITY_CODE                 VARCHAR2(64),
    QUALITY_STATUS               VARCHAR2(32),
    STATUS                       VARCHAR2(32),
    CERTIFICATE_NO               VARCHAR2(32),
    SUPPLY_CERIFICATE_NO         VARCHAR2(32),
    MOVE_QUANTITY                NUMBER(32,4),
    TRY_QUANTITY                 NUMBER(32,4),
    UNIT                         VARCHAR2(32),
    RECEIVER_SYS_USER            VARCHAR2(32),
    RECEIVER_HR_DEPT             VARCHAR2(32),
    IS_CONSIGNMENT               VARCHAR2(16),
    LAST_UPDATE_BY               VARCHAR2(32) not null,
    LAST_UPDATE_DATE             DATE         not null，
    DETAILS                      VARCHAR2(200),
    ATTRIBUTE_1                  VARCHAR2(32),
    ATTRIBUTE_2                  VARCHAR2(32),
    ATTRIBUTE_3                  VARCHAR2(32),
    ATTRIBUTE_4                  VARCHAR2(32),
    ATTRIBUTE_5                  VARCHAR2(32),
    ATTRIBUTE_6                  VARCHAR2(32),
    ATTRIBUTE_7                  VARCHAR2(32),
    ATTRIBUTE_8                  VARCHAR2(32),
    ATTRIBUTE_9                  VARCHAR2(32),
    ATTRIBUTE_10                 VARCHAR2(32),
    VERSION                      VARCHAR2(32)
)

comment on table WMS_MOVE_WAREHOUSE_BILL_SUB is '出库单子表';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.ID is '表id';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.BILL_CODE is '移库单号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.WAREHOUSE_LOCATION_CODE is '台账ID';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.ACCOUNT_ID is '库位号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.PRODUCTION_CODE is '产品编码';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.PRODUCTION_TYPE is '产品类型';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.IS_PARENT is '是否为父件，0父件、1子件、2非父子件';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.IS_PRODUCE is '是否为在制品';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.PARENT_PRODUCTION_CODE is '父产品编码';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.PROJECT_CODE is '项目编码';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.BRAND is '牌号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.SPECIFICATIONS is '规格';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.PRODUCTION_LEVEL is '状态/级别/型号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.TECHNICAL_CONDITIONS is '项目编码';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.ADDITIONAL_TECHNICAL_CONDITIONS is '附加技术条件';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.DRAW_CODE is '图号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.THREE_PERIOD_CODE is '三期代码';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.MANUFACTURE_DATA   is '生产日期';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.EXPIRATION_DATA is '过期日期';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.BATCH           is '批次号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.SPLYSOT_CODE    is '炉批号或小号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.AIRCRAFT_CODE   is '机型';,
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.SORTIE_CODE     is '架次';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.MODEL_CODE    is '版号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.CONSTRUCTION_CODE is '构型号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.QUALITY_STATUS     is '质检状态';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.QUALITY_CODE     is '质量编号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.STATUS              is '状态';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.CERTIFICATE_NO              is '合格证号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.SUPPLY_CERTIFICATE_NO  is '供方合格证号';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.MOVE_QUANTITY  is '需求数量';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.TRY_QUANTITY  is '化验消耗';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.UNIT                  is '主单位';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.RECEIVER_SYS_USER      is '接收人';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.RECEIVER_HR_DEPT        is '接收部门';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.LAST_UPDATED_BY          is '最后更新人';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.LAST_UPDATE_DATE          is '最后更新时间';
comment on column WMS_MOVE_WAREHOUSE_BILL_SUB.DETAILS                   is '备注';