create table WMS_WAREHOUSE_CATEGORY_INFO
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_WAREHOUSE_CATEGORY_INFO primary key,
    NAME          VARCHAR2(64) not null,
    CATEGORY_CODE VARCHAR2(32) not null,
    FATHER_CODE   VARCHAR2(32),
    VERSION       VARCHAR2(8),
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null,
    DETAILS       VARCHAR2(255)
);

comment on table WMS_WAREHOUSE_CATEGORY_INFO is '库房分类';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.ID is '表ID';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.NAME is '库房分类名称';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.CATEGORY_CODE is '库房分类编号';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.FATHER_CODE is '父分类编号';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.VERSION is '版本号';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.DETAILS is '描述';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.CREATED_BY is '创建人';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.CREATED_DATE is '创建时间';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.LAST_UPDATED_BY is '最后跟新人';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.LAST_UPDATED_DATE is '最后更新时间';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.DELETED_BY is '删除人';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.DELETED_DATE is '删除时间';
comment on column WMS_WAREHOUSE_CATEGORY_INFO.IS_DELETED is '是否删除，0为删除，1已经产出';

create index WMS_WAREHOUSE_CATEGORY_INFO_CATEGORYCODE on WMS_WAREHOUSE_CATEGORY_INFO (CATETORY_CODE);

create table WMS_WAREHOUSE_LOCATION
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_WAREHOUSE_LOCATION primary key,
    LOCATION_CODE    VARCHAR2(32),
    WAREHOUSE_CODE   VARCHAR2(32),
    LOCATION_TYPE  VARCHAR2(16),
    IS_EMPTY       VARCHAR2(8),
    STATE          VARCHAR2(16) default 'ok',
    LOCATION_SIZE  VARCHAR2(64),
    LENGTH         NUMBER(32,4),
    WIDTH         NUMBER(32,4),
    HEIGH         NUMBER(32,4),
    REMARKS        VARCHAR2(255),
    VERSION        VARCHAR2(8),
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null
);

comment on table WMS_WAREHOUSE_LOCATION is '库位定义';
comment on column WMS_WAREHOUSE_LOCATION.LOCATION_CODE is '库位号';
comment on column WMS_WAREHOUSE_LOCATION.WAREHOUSE_CODE is '库房编码';
comment on column WMS_WAREHOUSE_LOCATION.LOCATION_TYPE is '库位类型';
comment on column WMS_WAREHOUSE_LOCATION.IS_EMPTY is '是否为空库位';
comment on column WMS_WAREHOUSE_LOCATION.STATE is '状态';
comment on column WMS_WAREHOUSE_LOCATION.LOCATION_SIZE is '库位大小';
comment on column WMS_WAREHOUSE_LOCATION.LENGTH is '长，单位cm';
comment on column WMS_WAREHOUSE_LOCATION.WIDTH is '宽，单位cm';
comment on column WMS_WAREHOUSE_LOCATION.HEIGH is '高，单位cm';
comment on column WMS_WAREHOUSE_LOCATION.REMARKS is '备注';
comment on column WMS_WAREHOUSE_LOCATION.VERSION is '版本号';
comment on column WMS_WAREHOUSE_LOCATION.CREATED_BY is '创建人';
comment on column WMS_WAREHOUSE_LOCATION.CREATED_DATE is '创建时间';
comment on column WMS_WAREHOUSE_LOCATION.LAST_UPDATED_BY is '最后跟新人';
comment on column WMS_WAREHOUSE_LOCATION.LAST_UPDATED_DATE is '最后更新时间';
comment on column WMS_WAREHOUSE_LOCATION.DELETED_BY is '删除人';
comment on column WMS_WAREHOUSE_LOCATION.DELETED_DATE is '删除时间';
comment on column WMS_WAREHOUSE_LOCATION.IS_DELETED is '是否删除，0为删除，1已经产出';

create index WMS_WAREHOUSE_LOCATION_CODE on WMS_WAREHOUSE_LOCATION (LOCATION_CODE);
create index WMS_WAREHOUSE_LOCATION_WAREHOUSE_CODE on WMS_WAREHOUSE_LOCATION (WAREHOUSE_CODE);

create table WMS_WAREHOUSE
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint WMS_WAREHOUSE primary key,
    NAME               VARCHAR2(64),
    WAREHOUSE_CODE       VARCHAR2(32) not null,
    WAREHOUSE_TYPE     VARCHAR2(32),
    WAREHOUSE_CLASSIFY VARCHAR2(64),
    IS_AUTO            VARCHAR2(32) DEFAULT 'no',
    DEPARTMENT_NAME    VARCHAR2(64),
    DEPARTMENT_NO      VARCHAR2(32),
    PHONE              VARCHAR2(32),
    STATE              VARCHAR2(16) DEFAULT 'ok',
    CONNECT_STATE      VARCHAR2(8) DEFAULT 'offline',
    INVENTORY_TYPE     VARCHAR2(16),
    IS_VERIFICATION    VARCHAR2(8) DEFAULT 'no',
    IS_ACCOUNTING      VARCHAR2(8) DEFAULT 'no',
    VERIFICATION_TYPE  VARCHAR2(16),
    WAREHOUSE_LEVEL    VARCHAR2(8),
    PROJECT_CODE       VARCHAR2(32),
    KEYID              VARCHAR2(32),
    PLACE              VARCHAR2(255),
    VERSION            VARCHAR2(8),
    DETAILS            VARCHAR2(255),
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null
);

comment on table WMS_WAREHOUSE is '库房定义';
comment on column WMS_WAREHOUSE.ID is '库房ID';
comment on column WMS_WAREHOUSE.NAME is '库房名称';
comment on column WMS_WAREHOUSE.WAREHOUSE_CODE is '库房编码';
comment on column WMS_WAREHOUSE.WAREHOUSE_TYPE is '库房类型';
comment on column WMS_WAREHOUSE.IS_AUTO is '是否为自动仓';
comment on column WMS_WAREHOUSE.WAREHOUSE_CLASSIFY is '库房分类编码';
comment on column WMS_WAREHOUSE.DEPARTMENT_NO is '管理部门编号';
comment on column WMS_WAREHOUSE.DEPARTMENT_NAME is '管理部门名称';
comment on column WMS_WAREHOUSE.PHONE is '管理人员电话';
comment on column WMS_WAREHOUSE.STATE is '库房状态';
comment on column WMS_WAREHOUSE.CONNECT_STATE is '连接状态';
comment on column WMS_WAREHOUSE.INVENTORY_TYPE is '盘点类型';
comment on column WMS_WAREHOUSE.IS_VERIFICATION is '是否是核销库';
comment on column WMS_WAREHOUSE.VERIFICATION_TYPE is '核销类型';
comment on column WMS_WAREHOUSE.IS_ACCOUNTING  is '是否参与资金核算';
comment on column WMS_WAREHOUSE.WAREHOUSE_LEVEL   is '库房级别，大库、车间库';
comment on column WMS_WAREHOUSE.PLACE is '库房位置';
comment on column WMS_WAREHOUSE.VERSION is '版本号';
comment on column WMS_WAREHOUSE.DETAILS is '备注';
comment on column WMS_WAREHOUSE.CREATED_BY is '创建人';
comment on column WMS_WAREHOUSE.CREATED_DATE is '创建时间';
comment on column WMS_WAREHOUSE.LAST_UPDATED_BY is '最后跟新人';
comment on column WMS_WAREHOUSE.LAST_UPDATED_DATE is '最后更新时间';
comment on column WMS_WAREHOUSE.DELETED_BY is '删除人';
comment on column WMS_WAREHOUSE.DELETED_DATE is '删除时间';
comment on column WMS_WAREHOUSE.IS_DELETED is '是否删除，0为删除，1已经产出';

create index WMS_WAREHOUSE_CODE on WMS_WAREHOUSE (WAREHOUSE_CODE);

create table WMS_LOCATION_PRODUCTION
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_LOCATION_PRODUCTION primary key,
    WAREHOUSE_LOCATION_CODE VARCHAR2(32),
    WAREHOUSE_CODE          VARCHAR2(32),
    PRODUCTION_CODE         VARCHAR2(32),
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null
);

comment on table WMS_LOCATION_PRODUCTION is '库位物料绑定关系';
comment on column WMS_LOCATION_PRODUCTION.WAREHOUSE_LOCATION_CODE is '库位号';
comment on column WMS_LOCATION_PRODUCTION.WAREHOUSE_CODE is '库房号';
comment on column WMS_LOCATION_PRODUCTION.PRODUCTION_CODE is '物料编码';
comment on column WMS_LOCATION_PRODUCTION.CREATED_BY is '创建人';
comment on column WMS_LOCATION_PRODUCTION.CREATED_DATE is '创建时间';
comment on column WMS_LOCATION_PRODUCTION.LAST_UPDATED_BY is '最后跟新人';
comment on column WMS_LOCATION_PRODUCTION.LAST_UPDATED_DATE is '最后更新时间';
comment on column WMS_LOCATION_PRODUCTION.DELETED_BY is '删除人';
comment on column WMS_LOCATION_PRODUCTION.DELETED_DATE is '删除时间';
comment on column WMS_LOCATION_PRODUCTION.IS_DELETED is '是否删除，0为删除，1已经产出';

create table WMS_AUTO_WAREHOUSE_CONFIG
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint PK_WMS_AUTO_WAREHOUSE_CONFIG primary key,
    WAREHOUSE_CODE        VARCHAR2(32) not null,
    COMMUNICATION_PLACE VARCHAR2(255),
    AUTO_TYPE           VARCHAR2(32),
    STRATEGY            VARCHAR2(16),
    APP_KEY             VARCHAR2(32),
    APP_SECRET          VARCHAR2(256),
    VERSION             VARCHAR2(16),
    OPTIMIZATION_TYPE   VARCHAR2(32),
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null
);

comment on table WMS_AUTO_WAREHOUSE_CONFIG is '自动仓配置';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.WAREHOUSE_CODE is '库房编号';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.COMMUNICATION_PLACE is '通讯地址';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.AUTO_TYPE is '自动仓类型';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.STRATEGY is '自动仓调用类型，WMS、WCS';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.APP_KEY is '自动仓KEY';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.APP_SECRET is '自动仓密钥';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.VERSION is '版本号';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.OPTIMIZATION_TYPE is '自动仓存储优化策略';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.CREATED_BY is '创建人';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.CREATED_DATE is '创建时间';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.LAST_UPDATED_BY is '最后跟新人';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.LAST_UPDATED_DATE is '最后更新时间';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.DELETED_BY is '删除人';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.DELETED_DATE is '删除时间';
comment on column WMS_AUTO_WAREHOUSE_CONFIG.IS_DELETED is '是否删除，0为删除，1已经产出';

create index WMS_AUTO_WAREHOUSE_CONFIG_CODE on WMS_AUTO_WAREHOUSE_CONFIG (WAREHOUSE_CODE);

create table WMS_WAREHOUSE_TRANSACTIONS
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint WMS_WAREHOUSE_TRANSACTIONS primary key,
    NAME                VARCHAR2(64),
    WORK_CODE   VARCHAR2(32) not null,
    TRANSACTIONS_TYPE   VARCHAR2(32) not null,
    STATUS              VARCHAR2(32)  default 'ok',
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null
);

comment on table WMS_WAREHOUSE_TRANSACTIONS is '出入库事务';
comment on column WMS_WAREHOUSE_TRANSACTIONS.ID is '表ID';
comment on column WMS_WAREHOUSE_TRANSACTIONS.NAME is '事务名称';
comment on column WMS_WAREHOUSE_TRANSACTIONS.WORK_CODE is '事务编号';
comment on column WMS_WAREHOUSE_TRANSACTIONS.TRANSACTIONS_TYPE is '事务类型';
comment on column WMS_WAREHOUSE_TRANSACTIONS.STATUS is '状态';
comment on column WMS_WAREHOUSE_TRANSACTIONS.CREATED_BY is '创建人';
comment on column WMS_WAREHOUSE_TRANSACTIONS.CREATED_DATE is '创建时间';
comment on column WMS_WAREHOUSE_TRANSACTIONS.LAST_UPDATED_BY is '最后跟新人';
comment on column WMS_WAREHOUSE_TRANSACTIONS.LAST_UPDATED_DATE is '最后更新时间';
comment on column WMS_WAREHOUSE_TRANSACTIONS.DELETED_BY is '删除人';
comment on column WMS_WAREHOUSE_TRANSACTIONS.DELETED_DATE is '删除时间';
comment on column WMS_WAREHOUSE_TRANSACTIONS.IS_DELETED is '是否删除，0为删除，1已经产出';

create table WMS_WAREHOUSE_DEALS
(
    ID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY constraint WMS_WAREHOUSE_DEALS primary key,
    NAME                VARCHAR2(64) ,
    DEAL_CODE           VARCHAR2(32) not null,
    TRANSACTIONS_CODE   VARCHAR2(32),
    STATUS              VARCHAR2(32) default 'ok',
    CREATED_BY        VARCHAR2(32),
    CREATED_DATE      DATE       default SYSDATE not null,
    LAST_UPDATED_BY   VARCHAR2(32),
    LAST_UPDATED_DATE DATE       default SYSDATE not null,
    DELETED_BY        VARCHAR2(32),
    DELETED_DATE      DATE,
    IS_DELETED        NUMBER(2)  default 0       not null
);

comment on table WMS_WAREHOUSE_DEALS is '处理过程定义，对事务的一个补充，相当于子事务';
comment on column WMS_WAREHOUSE_DEALS.ID is '表ID';
comment on column WMS_WAREHOUSE_DEALS.NAME is '事务名称';
comment on column WMS_WAREHOUSE_DEALS.TRANSACTIONS_CODE is '事务编号';
comment on column WMS_WAREHOUSE_DEALS.DEAL_CODE is '处理编号';
comment on column WMS_WAREHOUSE_DEALS.STATUS is '状态';
comment on column WMS_WAREHOUSE_DEALS.CREATED_BY is '创建人';
comment on column WMS_WAREHOUSE_DEALS.CREATED_DATE is '创建时间';
comment on column WMS_WAREHOUSE_DEALS.LAST_UPDATED_BY is '最后跟新人';
comment on column WMS_WAREHOUSE_DEALS.LAST_UPDATED_DATE is '最后更新时间';
comment on column WMS_WAREHOUSE_DEALS.DELETED_BY is '删除人';
comment on column WMS_WAREHOUSE_DEALS.DELETED_DATE is '删除时间';
comment on column WMS_WAREHOUSE_DEALS.IS_DELETED is '是否删除，0为删除，1已经产出';